export const seedDeals = [
  // ─────────────────────────────────────────────
  // 1940s
  // ─────────────────────────────────────────────
  {
    title: "India–USA Grain Aid Agreement (PL-480)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "First major American food aid to newly independent India under Public Law 480, providing surplus wheat to address food scarcity.",
    strategicIntent: "Secure food supply for a newly independent nation facing famine conditions.",
    whyIndiaNeedsThis: "India faced acute food shortages post-partition and needed immediate grain imports.",
    keyItems: ["Wheat imports", "Concessional rupee payments", "Agricultural cooperation"],
    date: "1947"
  },
  {
    title: "Colombo Plan Membership",
    country: "United Kingdom",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India joined the Colombo Plan for cooperative economic and social development in Asia and the Pacific.",
    strategicIntent: "Access development aid and technical assistance from Commonwealth nations.",
    whyIndiaNeedsThis: "Framework for multilateral development cooperation for newly independent India.",
    keyItems: ["Technical assistance", "Capital aid", "Regional cooperation"],
    date: "1950"
  },
  // ─────────────────────────────────────────────
  // 1950s
  // ─────────────────────────────────────────────
  {
    title: "India–USA Point Four Programme",
    country: "USA",
    value: "0.05B",
    status: "Completed",
    type: "Technology",
    impact: "Medium Impact",
    description: "Technical assistance agreement under President Truman's Point Four Programme for agricultural and industrial development.",
    strategicIntent: "Modernise Indian agriculture and industry through American technical know-how.",
    whyIndiaNeedsThis: "India needed technical expertise to build industrial and agricultural capacity from scratch.",
    keyItems: ["Agricultural extension programs", "Technical training", "Industrial demonstrations"],
    date: "1952"
  },
  {
    title: "India–Soviet Union Trade Agreement",
    country: "Russia",
    value: "0.1B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "First major trade agreement between India and the Soviet Union, establishing bilateral trade relations.",
    strategicIntent: "Diversify trade away from former colonial powers and build relations with socialist bloc.",
    whyIndiaNeedsThis: "Non-alignment policy required balancing trade between Western and Eastern blocs.",
    keyItems: ["Rupee-Ruble trade", "Machinery exports from USSR", "Indian cotton and textiles"],
    date: "1953"
  },
  {
    title: "Bhilai Steel Plant Agreement",
    country: "Russia",
    value: "0.15B",
    status: "Completed",
    type: "Technology",
    impact: "High Impact",
    description: "Soviet Union agreed to build the Bhilai Steel Plant in Chhattisgarh, India's first modern integrated steel plant.",
    strategicIntent: "Build India's heavy industrial base and reduce dependence on imports.",
    whyIndiaNeedsThis: "India's First Five Year Plan prioritised steel production for industrialisation.",
    keyItems: ["1 million ton steel plant", "Technology transfer", "Soviet technical experts"],
    date: "February 1955"
  },
  {
    title: "Rourkela Steel Plant (German Collaboration)",
    country: "Germany",
    value: "0.1B",
    status: "Completed",
    type: "Technology",
    impact: "High Impact",
    description: "West Germany agreed to build the Rourkela Steel Plant in Odisha as part of India's industrialisation drive.",
    strategicIntent: "Establish India's steel industry through foreign collaboration.",
    whyIndiaNeedsThis: "India needed multiple steel plants to meet growing demand and reduce imports.",
    keyItems: ["Steel plant construction", "German technology transfer", "Training of Indian engineers"],
    date: "1955"
  },
  {
    title: "Durgapur Steel Plant (British Collaboration)",
    country: "United Kingdom",
    value: "0.1B",
    status: "Completed",
    type: "Technology",
    impact: "High Impact",
    description: "UK agreed to build the Durgapur Steel Plant in West Bengal, part of the three-nation steel plant initiative.",
    strategicIntent: "Maintain Commonwealth ties while building domestic industrial capacity.",
    whyIndiaNeedsThis: "Three major steel plants were needed to feed India's Second Five Year Plan targets.",
    keyItems: ["Steel plant construction", "British Steelwork Associates involvement", "1 million ton capacity"],
    date: "1956"
  },
  {
    title: "India–USA Atomic Energy Agreement",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "Bilateral agreement for peaceful nuclear cooperation under the 'Atoms for Peace' programme.",
    strategicIntent: "Develop civilian nuclear energy capability to power India's growing economy.",
    whyIndiaNeedsThis: "India needed nuclear technology to develop an independent energy sector.",
    keyItems: ["Research reactor APSARA", "Nuclear fuel supply", "Technical training"],
    date: "August 1956"
  },
  {
    title: "Apsara Research Reactor (Canadian Collaboration)",
    country: "Canada",
    value: "0",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "Canada supplied the CIRUS reactor to India under the Colombo Plan, a critical stepping stone in India's nuclear programme.",
    strategicIntent: "Develop indigenous nuclear research and energy capability.",
    whyIndiaNeedsThis: "India needed a research reactor to train nuclear scientists and generate plutonium.",
    keyItems: ["40 MW research reactor", "Heavy water supply", "Nuclear training"],
    date: "1956"
  },
  {
    title: "Indus Waters Treaty",
    country: "Pakistan",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Water-distribution treaty brokered by the World Bank between India and Pakistan for the Indus river system.",
    strategicIntent: "Manage the use of the Indus River system's waters fairly between the two nations.",
    whyIndiaNeedsThis: "Ensured agricultural security for the Punjab and Sindh regions via controlled river access.",
    keyItems: ["Allocation of Beas, Ravi, and Sutlej to India", "Allocation of Indus, Chenab, and Jhelum to Pakistan", "World Bank mediation"],
    date: "September 1960"
  },
  // ─────────────────────────────────────────────
  // 1960s
  // ─────────────────────────────────────────────
  {
    title: "India–Soviet MiG-21 License Production Agreement",
    country: "Russia",
    value: "0.3B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Landmark agreement for license production of MiG-21 fighter aircraft in India at HAL Nasik.",
    strategicIntent: "Build domestic fighter aircraft manufacturing capability and modernise IAF.",
    whyIndiaNeedsThis: "India needed modern supersonic fighters and indigenous production capability after 1962 war.",
    keyItems: ["MiG-21 aircraft", "License production at HAL", "Technology transfer"],
    date: "1962"
  },
  {
    title: "India–USA Tarapur Nuclear Power Agreement",
    country: "USA",
    value: "0.08B",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "Agreement for the US to build India's first nuclear power plant at Tarapur, Maharashtra.",
    strategicIntent: "Develop civilian nuclear power generation capacity in India.",
    whyIndiaNeedsThis: "India needed nuclear power plants to meet growing electricity demand.",
    keyItems: ["Two 200 MW BWR reactors", "US fuel supply commitment", "Training of Indian nuclear engineers"],
    date: "1963"
  },
  {
    title: "Indo–Soviet Treaty of Peace, Friendship and Cooperation",
    country: "Russia",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "20-year treaty of friendship between India and the Soviet Union, providing Soviet backing in case of external aggression.",
    strategicIntent: "Secure a strategic partner during the 1971 Bangladesh War and counter US-China-Pakistan alliance.",
    whyIndiaNeedsThis: "India needed diplomatic cover during the 1971 Bangladesh Liberation War.",
    keyItems: ["Mutual consultation clause", "Soviet naval deployment deterrence", "Arms supply guarantee"],
    date: "August 1971"
  },
  {
    title: "India–Soviet Arms Supply Agreement (1971 War)",
    country: "Russia",
    value: "0.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Emergency arms supply by USSR to India during 1971 Indo-Pak War including tanks, aircraft, and naval vessels.",
    strategicIntent: "Ensure decisive military victory and creation of Bangladesh.",
    whyIndiaNeedsThis: "India needed rapid arms resupply to sustain a two-front war against Pakistan.",
    keyItems: ["T-55 tanks", "Aircraft ammunition", "Naval vessels"],
    date: "December 1971"
  },
  // ─────────────────────────────────────────────
  // 1970s
  // ─────────────────────────────────────────────
  {
    title: "India–UK Jaguar Aircraft Deal",
    country: "United Kingdom",
    value: "1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased Jaguar strike aircraft from the UK/France SEPECAT consortium and licensed HAL to produce them.",
    strategicIntent: "Replace ageing Canberra bombers and provide deep-strike capability to IAF.",
    whyIndiaNeedsThis: "IAF needed a modern ground-attack aircraft after 1971 war experience.",
    keyItems: ["120 Jaguar aircraft", "HAL license production", "Adour engine manufacturing"],
    date: "1978"
  },
  {
    title: "India–Soviet Kilo Class Submarine Deal",
    country: "Russia",
    value: "0.8B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India acquired Kilo-class diesel-electric submarines from the Soviet Union to build undersea warfare capability.",
    strategicIntent: "Develop India's submarine fleet and underwater warfare capability in the Indian Ocean.",
    whyIndiaNeedsThis: "IN had limited submarine capability; Kilo class gave it blue-water deterrence.",
    keyItems: ["10 Kilo-class submarines", "Submarine crew training", "Maintenance support"],
    date: "1980"
  },
  // ─────────────────────────────────────────────
  // 1980s
  // ─────────────────────────────────────────────
  {
    title: "India–Soviet INS Chakra (Charlie-I) Lease",
    country: "Russia",
    value: "0",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India leased a Soviet Charlie-I class nuclear-powered submarine, becoming the sixth nation to operate a nuclear submarine.",
    strategicIntent: "Train Indian Navy crew on nuclear submarine operations and demonstrate blue-water capability.",
    whyIndiaNeedsThis: "India needed nuclear submarine operating experience for its future ATV (Arihant) programme.",
    keyItems: ["Charlie-I SSGN", "3-year lease", "Crew training"],
    date: "January 1988"
  },
  {
    title: "India–France Mirage 2000 Deal",
    country: "France",
    value: "2.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased Mirage 2000 multi-role fighters from France, which later played a decisive role in the Kargil War.",
    strategicIntent: "Acquire advanced multi-role combat aircraft with beyond-visual-range capability.",
    whyIndiaNeedsThis: "IAF needed modern 4th-gen fighters as the MiG-21 fleet was ageing.",
    keyItems: ["36 Mirage 2000H/TH aircraft", "SNECMA M53 engines", "Magic and Super 530D missiles"],
    date: "1982"
  },
  {
    title: "BrahMos Cruise Missile Joint Development",
    country: "Russia",
    value: "0.5B",
    status: "Ongoing",
    type: "Technology",
    impact: "High Impact",
    description: "A joint venture between India's DRDO and Russia's NPO Mashinostroyenia to develop the BrahMos supersonic cruise missile.",
    strategicIntent: "Develop world's fastest supersonic cruise missile for land, sea, and air platforms.",
    whyIndiaNeedsThis: "Enhance precision strike capability and maritime dominance in the Indian Ocean.",
    keyItems: ["Propulsion technology", "Missile airframes", "Joint marketing and export"],
    date: "February 1998"
  },
  // ─────────────────────────────────────────────
  // 1990s
  // ─────────────────────────────────────────────
  {
    title: "India–Russia INS Chakra-II Lease Agreement",
    country: "Russia",
    value: "0.9B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India leased Akula-II class nuclear submarine INS Chakra from Russia for 10 years.",
    strategicIntent: "Maintain nuclear submarine operating experience while Arihant class was under construction.",
    whyIndiaNeedsThis: "India needed continuous nuclear submarine operations training.",
    keyItems: ["Akula-II class SSGN", "10-year lease", "Nuclear propulsion training"],
    date: "2012"
  },
  {
    title: "India–WTO Membership",
    country: "Multilateral",
    value: "0",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "India became a founding member of the World Trade Organization, replacing the GATT framework.",
    strategicIntent: "Integrate India into the global rules-based trading order and protect Indian trade interests.",
    whyIndiaNeedsThis: "WTO membership gave India formal multilateral dispute settlement and market access rights.",
    keyItems: ["Tariff bindings", "TRIPS compliance", "Dispute settlement access"],
    date: "January 1995"
  },
  {
    title: "India–USA General Electric F404 Engine Deal (LCA Tejas)",
    country: "USA",
    value: "0.1B",
    status: "Completed",
    type: "Technology",
    impact: "Medium Impact",
    description: "India procured GE F404 turbofan engines from the USA to power the indigenous Light Combat Aircraft (LCA) Tejas.",
    strategicIntent: "Overcome engine development bottleneck and keep India's LCA programme on track.",
    whyIndiaNeedsThis: "India's indigenous Kaveri engine programme was delayed; a foreign engine kept Tejas flying.",
    keyItems: ["GE F404-GE-F2J3 engines", "Technology co-development terms", "HAL integration work"],
    date: "1998"
  },
  // ─────────────────────────────────────────────
  // 2000s
  // ─────────────────────────────────────────────
  {
    title: "India–Russia Admiral Gorshkov (INS Vikramaditya) Aircraft Carrier Deal",
    country: "Russia",
    value: "2.9B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India acquired and refurbished the Kiev-class carrier Admiral Gorshkov from Russia, renamed INS Vikramaditya.",
    strategicIntent: "Maintain carrier aviation capability after decommissioning of INS Viraat.",
    whyIndiaNeedsThis: "India needed a carrier to project power in the Indian Ocean and train naval aviators.",
    keyItems: ["45,000-ton carrier", "MiG-29K aircraft package", "Extensive refit at Sevmash"],
    date: "2004"
  },
  {
    title: "India–USA Civil Nuclear Deal (123 Agreement)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "The historic framework for civil nuclear cooperation, lifting the global nuclear trade embargo on India.",
    strategicIntent: "Secure reliable energy sources for India's growing economy while gaining de facto recognition as a nuclear power.",
    whyIndiaNeedsThis: "India was isolated from global nuclear technology since 1974; this deal allowed import of uranium and reactors.",
    keyItems: ["Separation of civil and military nuclear facilities", "IAEA safeguards compliance", "Access to US nuclear technology"],
    date: "October 2008"
  },
  {
    title: "India–Russia MiG-29K Naval Fighter Deal",
    country: "Russia",
    value: "1.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased MiG-29K/KUB carrier-borne fighters for INS Vikramaditya and future INS Vikrant.",
    strategicIntent: "Provide carrier aviation strike and fleet air defence capability to the Indian Navy.",
    whyIndiaNeedsThis: "India's carrier air wing needed a modern supersonic fighter to replace the Sea Harrier.",
    keyItems: ["45 MiG-29K/KUB aircraft", "Training simulators", "Full support package"],
    date: "2004"
  },
  {
    title: "India–Israel Phalcon AWACS Deal",
    country: "Israel",
    value: "1.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India acquired three Phalcon Airborne Warning and Control System aircraft mounted on Russian IL-76 platforms.",
    strategicIntent: "Provide India with advanced airborne surveillance and battle management capability.",
    whyIndiaNeedsThis: "IAF needed AEW&C capability to monitor large airspace during conflicts.",
    keyItems: ["3 Phalcon AWACS", "ELM-2075 radar", "Datalink integration with IAF fighters"],
    date: "2004"
  },
  {
    title: "India–France Scorpene Submarine Deal",
    country: "France",
    value: "3.75B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India contracted DCNS (now Naval Group) to build six Scorpene-class diesel-electric submarines at Mazagon Dock, Mumbai.",
    strategicIntent: "Expand India's conventional submarine fleet and build undersea manufacturing capability.",
    whyIndiaNeedsThis: "India's submarine fleet was ageing; new boats were critical for underwater deterrence.",
    keyItems: ["6 Scorpene submarines", "Technology transfer to MDL", "AIP system for future boats"],
    date: "October 2005"
  },
  {
    title: "India–USA NSSP and Defence Cooperation Agreement",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Next Steps in Strategic Partnership and formal defence cooperation framework between India and the USA.",
    strategicIntent: "Transform India-US relationship from transactional to strategic and defence partnership.",
    whyIndiaNeedsThis: "India needed US cooperation in high-tech areas including space, nuclear, and defence.",
    keyItems: ["Defence technology transfer", "Space cooperation", "Civil nuclear pathway"],
    date: "2005"
  },
  {
    title: "India–Afghanistan Strategic Partnership Agreement",
    country: "Afghanistan",
    value: "2B",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "India signed its first strategic partnership agreement with Afghanistan, pledging development and security assistance.",
    strategicIntent: "Build influence in Afghanistan, counter Pakistani proxy strategies, and secure regional stability.",
    whyIndiaNeedsThis: "A stable Afghanistan serves India's strategic depth and trade corridor interests.",
    keyItems: ["Parliament building construction", "Salma Dam (Afghan-India Friendship Dam)", "Zaranj-Delaram highway"],
    date: "2011"
  },
  {
    title: "India–Russia S-400 Triumf Missile System Purchase",
    country: "Russia",
    value: "5.4B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Contract for five squadrons of the S-400 air defence system.",
    strategicIntent: "Provide a long-range surface-to-air missile shield for major cities and strategic assets.",
    whyIndiaNeedsThis: "Counter threats from advanced aerial platforms and ballistic missiles along long border stretches.",
    keyItems: ["5 S-400 Regiments", "Command and Control centers", "Radar systems"],
    date: "October 2018"
  },
  {
    title: "India–Japan CEPA (Comprehensive Economic Partnership Agreement)",
    country: "Japan",
    value: "15B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "Comprehensive Economic Partnership Agreement between India and Japan covering trade in goods, services, and investment.",
    strategicIntent: "Boost bilateral trade, attract Japanese investment, and integrate supply chains.",
    whyIndiaNeedsThis: "Japan was India's top infrastructure and FDI partner; a CEPA formalised and deepened the relationship.",
    keyItems: ["Tariff reduction on 90% goods", "Investment promotion", "Services liberalisation"],
    date: "August 2011"
  },
  {
    title: "India–South Korea CEPA",
    country: "South Korea",
    value: "12B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "Comprehensive Economic Partnership Agreement between India and South Korea.",
    strategicIntent: "Expand trade in electronics, automotive, and pharmaceuticals.",
    whyIndiaNeedsThis: "Korea offered tech transfer and FDI in manufacturing sectors India needed to develop.",
    keyItems: ["Tariff concessions", "Investment facilitation", "Technology collaboration"],
    date: "January 2010"
  },
  // ─────────────────────────────────────────────
  // 2010s
  // ─────────────────────────────────────────────
  {
    title: "India–USA C-17 Globemaster III Transport Aircraft Deal",
    country: "USA",
    value: "4.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased 10 C-17 Globemaster III strategic airlift aircraft from Boeing for the Indian Air Force.",
    strategicIntent: "Build strategic airlift capability for rapid troop and equipment deployment across India and abroad.",
    whyIndiaNeedsThis: "IAF needed heavy strategic transport aircraft for operations in high-altitude areas and disaster relief.",
    keyItems: ["10 C-17 aircraft", "Strategic airlift capability", "Humanitarian assistance role"],
    date: "2011"
  },
  {
    title: "India–USA P-8I Poseidon Maritime Patrol Aircraft Deal",
    country: "USA",
    value: "2.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased Boeing P-8I Poseidon maritime patrol and ASW aircraft for the Indian Navy.",
    strategicIntent: "Dominate the Indian Ocean with advanced sub-hunting and maritime surveillance capability.",
    whyIndiaNeedsThis: "China's expanding submarine operations in the Indian Ocean required superior ASW capability.",
    keyItems: ["12 P-8I aircraft", "Harpoon missiles", "Sonobuoy systems"],
    date: "2009"
  },
  {
    title: "India–Israel Barak-8 Missile System Deal",
    country: "Israel",
    value: "2B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Joint India-Israel development and procurement of the Barak-8 medium-range surface-to-air missile system.",
    strategicIntent: "Provide naval and land-based air defence against aircraft, missiles, and drones.",
    whyIndiaNeedsThis: "India needed modern SAM systems for naval vessels and land forces.",
    keyItems: ["Barak-8 missiles", "MRSAM land version", "Joint production by DRDO and IAI"],
    date: "2009"
  },
  {
    title: "India–France Rafale Fighter Jet Deal (36 Aircraft)",
    country: "France",
    value: "8.7B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased 36 Rafale multi-role combat aircraft from France in government-to-government deal.",
    strategicIntent: "Rapidly bridge IAF's combat capability gap with a battle-proven 4.5-gen fighter.",
    whyIndiaNeedsThis: "IAF was down to 30 squadrons against a required 42; Rafale was the quickest solution.",
    keyItems: ["36 Rafale F3R jets", "Meteor BVR missiles", "SCALP cruise missiles", "India-specific enhancements"],
    date: "September 2016"
  },
  {
    title: "India–USA COMCASA (Communications Compatibility and Security Agreement)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "India signed the Communications Compatibility and Security Agreement with the USA enabling encrypted military communications.",
    strategicIntent: "Enable real-time data sharing between Indian and US military platforms.",
    whyIndiaNeedsThis: "India could not receive encrypted communications with US-origin systems without COMCASA.",
    keyItems: ["Encrypted comms capability", "US platform data links", "Interoperability with US forces"],
    date: "September 2018"
  },
  {
    title: "India–USA BECA (Basic Exchange and Cooperation Agreement)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "India signed the Basic Exchange and Cooperation Agreement enabling sharing of geospatial intelligence and maps.",
    strategicIntent: "Enhance precision targeting and navigation for Indian missiles and military systems.",
    whyIndiaNeedsThis: "Indian missiles and aircraft would gain GPS-accuracy using US geospatial data.",
    keyItems: ["Geospatial intelligence sharing", "Precision navigation data", "Topographic mapping"],
    date: "October 2020"
  },
  {
    title: "India–USA LEMOA (Logistics Exchange Memorandum of Agreement)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "India signed the Logistics Exchange MOU with the USA allowing mutual use of military facilities for logistics.",
    strategicIntent: "Enable Indian and US forces to resupply and refuel at each other's bases globally.",
    whyIndiaNeedsThis: "India needed logistics support for long-range operations and disaster relief missions.",
    keyItems: ["Mutual base access", "Fuel and logistics sharing", "Navy port calls"],
    date: "August 2016"
  },
  {
    title: "India–Israel Defense Trade and R&D Partnership",
    country: "Israel",
    value: "5B",
    status: "Ongoing",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Broad defence partnership making Israel one of India's top arms suppliers including drones, missiles, and electronics.",
    strategicIntent: "Access cutting-edge Israeli drone, missile, and electronic warfare technology.",
    whyIndiaNeedsThis: "Israeli systems like Heron drones and Barak missiles filled critical IAF/IN capability gaps.",
    keyItems: ["Heron drones", "Harop loitering munitions", "EW systems", "Spike ATGMs"],
    date: "2000"
  },
  {
    title: "India–Japan Special Strategic and Global Partnership",
    country: "Japan",
    value: "35B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Elevation of India-Japan ties to Special Strategic and Global Partnership including bullet train, infrastructure, and defence cooperation.",
    strategicIntent: "Counter China's influence with a like-minded democratic partner.",
    whyIndiaNeedsThis: "Japan's capital and technology are vital for India's smart cities, bullet train, and digital infrastructure.",
    keyItems: ["Mumbai-Ahmedabad bullet train", "JPY 50,000 crore ODA", "Defence technology cooperation"],
    date: "2014"
  },
  {
    title: "India–UAE Comprehensive Economic Partnership Agreement",
    country: "UAE",
    value: "100B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "First bilateral free trade agreement signed by India in a decade, with UAE being India's second largest trading partner.",
    strategicIntent: "Boost bilateral trade, remittances, and investment from Gulf region.",
    whyIndiaNeedsThis: "UAE hosts 3.5 million Indian diaspora and is India's gateway to Gulf trade.",
    keyItems: ["Zero tariff on 80% Indian goods", "Investment facilitation", "Services liberalisation"],
    date: "May 2022"
  },
  {
    title: "India–Australia ECTA (Economic Cooperation and Trade Agreement)",
    country: "Australia",
    value: "45B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "Interim free trade agreement between India and Australia covering goods, services, and investment.",
    strategicIntent: "Deepen trade ties with a key Quad partner and diversify supply chains.",
    whyIndiaNeedsThis: "Australia supplies critical minerals, education, and commodities India needs.",
    keyItems: ["Zero duty on Australian coal, sheep meat, wool", "Duty-free Indian textiles and pharma", "Critical minerals cooperation"],
    date: "December 2022"
  },
  {
    title: "India–GCC Free Trade Agreement Negotiations",
    country: "Saudi Arabia",
    value: "0",
    status: "Proposed",
    type: "Trade",
    impact: "High Impact",
    description: "Ongoing negotiations for a free trade agreement between India and the Gulf Cooperation Council.",
    strategicIntent: "Secure India's largest trade partner region in a formal trade framework.",
    whyIndiaNeedsThis: "Gulf countries are India's largest oil suppliers and host 9 million Indian workers.",
    keyItems: ["Tariff reduction on Indian goods", "Services liberalisation", "Investment protection"],
    date: "2023"
  },
  // ─────────────────────────────────────────────
  // 2020s
  // ─────────────────────────────────────────────
  {
    title: "India–USA iCET (Initiative on Critical and Emerging Technologies)",
    country: "USA",
    value: "0",
    status: "Ongoing",
    type: "Technology",
    impact: "High Impact",
    description: "Landmark initiative for co-development of critical technologies including semiconductors, AI, quantum computing, and defence.",
    strategicIntent: "Build technological self-reliance with US partnership in cutting-edge sectors.",
    whyIndiaNeedsThis: "India needs access to US tech ecosystem to achieve technological leadership.",
    keyItems: ["Semiconductor ecosystem", "AI and quantum computing", "GE F414 engine co-production for Tejas Mk2"],
    date: "January 2023"
  },
  {
    title: "India–USA GE F414 Engine Deal for Tejas Mk2",
    country: "USA",
    value: "0.7B",
    status: "In Progress",
    type: "Technology",
    impact: "High Impact",
    description: "USA agreed to transfer 80% technology for GE F414 turbofan engines to India for production at HAL.",
    strategicIntent: "Achieve strategic engine manufacturing capability and power the Tejas Mk2 fighter.",
    whyIndiaNeedsThis: "India's Kaveri engine programme remains incomplete; F414 production will bridge the gap.",
    keyItems: ["F414 engine production at HAL", "80% technology transfer", "200 engines for Tejas Mk2"],
    date: "2023"
  },
  {
    title: "India–USA MQ-9B Predator Drone Deal",
    country: "USA",
    value: "3.07B",
    status: "Proposed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India to purchase 31 MQ-9B SeaGuardian and SkyGuardian armed drones from General Atomics for tri-services.",
    strategicIntent: "Provide India with persistent ISR and armed strike capability over land and sea.",
    whyIndiaNeedsThis: "India needs long-endurance armed drones to monitor Chinese build-up along LAC and in IOR.",
    keyItems: ["15 SeaGuardian for Navy", "8 for Army", "8 for IAF", "Hellfire missiles"],
    date: "2023"
  },
  {
    title: "India–Russia INS Chakra-III Nuclear Submarine Lease",
    country: "Russia",
    value: "3B",
    status: "Proposed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India is negotiating lease of a third nuclear-powered attack submarine from Russia.",
    strategicIntent: "Maintain nuclear undersea deterrence while domestic Arihant-class SSBNs are under construction.",
    whyIndiaNeedsThis: "India needs SSN capability to counter China's growing submarine fleet in the IOR.",
    keyItems: ["Akula-II class SSN", "10-year lease", "Crew training"],
    date: "2024"
  },
  {
    title: "114 Rafale MRFA Deal (Multi-Role Fighter Aircraft)",
    country: "France",
    value: "40B",
    status: "Proposed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India's cabinet approved a massive ₹3.25 lakh crore (~$40B) deal for 114 Rafale MRFA jets to replace ageing MiG-21 and Jaguar fleets.",
    strategicIntent: "Modernise IAF combat fleet, achieve 42-squadron strength, and build fighter jet manufacturing capability domestically.",
    whyIndiaNeedsThis: "IAF currently has only 30 squadrons against required 42. MiG-21s are being phased out; India needs advanced MRCA jets urgently.",
    keyItems: ["114 Rafale jets (18 in fly-away condition, 96 to be built in India)", "Technology Transfer to HAL", "Weapon systems including Meteor, MICA, SCALP missiles"],
    date: "February 2025"
  },
  {
    title: "India–European Union Free Trade Agreement",
    country: "European Union",
    value: "500B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "A comprehensive free trade agreement concluded between India and the European Union on January 27, 2026.",
    strategicIntent: "Enhance bilateral trade relations and economic cooperation.",
    whyIndiaNeedsThis: "Diversify trade partnerships and reduce dependence on traditional markets.",
    keyItems: ["Reduction of tariffs on goods", "Enhanced economic cooperation", "Trade liberalization"],
    date: "January 2026"
  },
  {
    title: "India–Quad Security Framework",
    country: "USA",
    value: "0",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Quadrilateral Security Dialogue between India, USA, Japan, and Australia for a free and open Indo-Pacific.",
    strategicIntent: "Counter Chinese military and economic assertiveness in the Indo-Pacific.",
    whyIndiaNeedsThis: "India needs multilateral backing to balance against Chinese threats across LAC and IOR.",
    keyItems: ["Joint naval exercises (Malabar)", "Vaccine and technology initiatives", "Critical infrastructure protection"],
    date: "2021"
  },
  {
    title: "India–Maldives Development Partnership",
    country: "Maldives",
    value: "1.4B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India's development assistance to Maldives including infrastructure, health, and connectivity projects.",
    strategicIntent: "Maintain strategic influence in the Indian Ocean island nation and counter Chinese infrastructure investments.",
    whyIndiaNeedsThis: "Maldives sits astride key shipping lanes; Indian influence ensures IOR stability.",
    keyItems: ["Greater Male Connectivity Project", "Health sector support", "Airport development"],
    date: "2020"
  },
  {
    title: "India–Sri Lanka Economic Cooperation",
    country: "Sri Lanka",
    value: "4B",
    status: "Ongoing",
    type: "Trade",
    impact: "Medium Impact",
    description: "Comprehensive assistance package during Sri Lanka's economic crisis and long-term development cooperation.",
    strategicIntent: "Maintain strategic neighbourhood influence and counter China's debt-trap diplomacy.",
    whyIndiaNeedsThis: "Sri Lanka is critical to India's southern maritime security and Indian Ocean strategy.",
    keyItems: ["Currency swap lines", "Fuel supply", "Trincomalee energy zone development"],
    date: "2022"
  },
  {
    title: "India–Bangladesh Teesta Water Treaty (Pending)",
    country: "Bangladesh",
    value: "0",
    status: "Proposed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Long-pending agreement for equitable distribution of Teesta river waters between India and Bangladesh.",
    strategicIntent: "Cement bilateral ties with Bangladesh and address a major source of friction.",
    whyIndiaNeedsThis: "Bangladesh is India's largest trade partner in South Asia; resolving Teesta will deepen ties.",
    keyItems: ["Water sharing formula", "Joint river commission", "Agricultural cooperation"],
    date: "Pending"
  },
  {
    title: "India–Nepal Power Trade Agreement",
    country: "Nepal",
    value: "5B",
    status: "Ongoing",
    type: "Energy",
    impact: "High Impact",
    description: "India agreed to purchase 10,000 MW of hydroelectric power from Nepal over 10 years.",
    strategicIntent: "Meet India's growing power needs from clean energy and integrate Nepal economically.",
    whyIndiaNeedsThis: "Nepal's vast hydro potential can power India's northern states sustainably.",
    keyItems: ["10,000 MW hydro power purchase", "Cross-border transmission lines", "Joint project development"],
    date: "2023"
  },
  {
    title: "India–Saudi Arabia Strategic Partnership Council",
    country: "Saudi Arabia",
    value: "75B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Comprehensive strategic partnership including energy, defence, investment, and cultural ties.",
    strategicIntent: "Secure oil supply, attract Gulf investments, and deepen ties with the Arab world's largest economy.",
    whyIndiaNeedsThis: "Saudi Arabia is India's top oil supplier and home to 2.5 million Indian workers.",
    keyItems: ["$75B investment pledge", "Oil supply security", "Defence cooperation", "UPI payment interoperability"],
    date: "2019"
  },
  {
    title: "India–China Border Trade Agreements",
    country: "China",
    value: "0",
    status: "Completed",
    type: "Trade",
    impact: "Medium Impact",
    description: "Series of agreements on border trade including Nathula Pass reopening and border haats.",
    strategicIntent: "Manage economic relations with China despite political tensions.",
    whyIndiaNeedsThis: "China is India's largest trading partner; managing border trade reduces friction.",
    keyItems: ["Nathula Pass trade route", "Border haats in Northeast", "Trade facilitation measures"],
    date: "2006"
  },
  {
    title: "India–Israel Free Trade Agreement Negotiations",
    country: "Israel",
    value: "10B",
    status: "In Progress",
    type: "Trade",
    impact: "Medium Impact",
    description: "Ongoing negotiations for a free trade agreement between India and Israel.",
    strategicIntent: "Formalise trade and technology ties with Israel beyond defence cooperation.",
    whyIndiaNeedsThis: "Israel offers agri-tech, water tech, and cybersecurity expertise India urgently needs.",
    keyItems: ["Technology trade liberalisation", "Agri-tech cooperation", "Pharma market access"],
    date: "2022"
  },
  {
    title: "India–Canada Potash Import Agreement",
    country: "Canada",
    value: "0.5B",
    status: "Ongoing",
    type: "Trade",
    impact: "Medium Impact",
    description: "Long-term agreements for India to import potash fertiliser from Canada.",
    strategicIntent: "Secure fertiliser supplies for Indian agriculture.",
    whyIndiaNeedsThis: "India imports 90% of its potash; Canada is the world's largest producer.",
    keyItems: ["Potash supply agreements", "Competitive pricing", "Agricultural cooperation"],
    date: "2000"
  },
  {
    title: "India–Russia Oil Purchase Agreements (Post-Ukraine)",
    country: "Russia",
    value: "50B",
    status: "Ongoing",
    type: "Trade",
    impact: "High Impact",
    description: "India massively scaled up discounted crude oil imports from Russia following Western sanctions post-Ukraine war.",
    strategicIntent: "Secure cheap oil to manage inflation and reduce India's energy import bill.",
    whyIndiaNeedsThis: "Russian crude at $20-30 discounts to Brent saved India billions in forex outgo.",
    keyItems: ["Discounted crude oil", "Rupee-Ruble payment mechanism", "Refinery upgrades for Urals crude"],
    date: "2022"
  },
  {
    title: "India–Iran Chabahar Port Agreement",
    country: "Iran",
    value: "0.85B",
    status: "In Progress",
    type: "Trade",
    impact: "High Impact",
    description: "India contracted to develop and operate the Shahid Beheshti terminal at Chabahar Port in Iran for 10 years.",
    strategicIntent: "Create a trade corridor to Afghanistan and Central Asia bypassing Pakistan.",
    whyIndiaNeedsThis: "Chabahar gives India direct access to Afghanistan and Central Asian markets without Pakistani territory.",
    keyItems: ["Port terminal development", "Rail link to Zahedan", "INSTC route integration"],
    date: "2016"
  },
  {
    title: "India–ASEAN FTA (Free Trade in Goods Agreement)",
    country: "ASEAN",
    value: "100B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "Free trade agreement between India and the 10 ASEAN member nations on trade in goods.",
    strategicIntent: "Integrate India into Southeast Asian supply chains and boost Act East Policy.",
    whyIndiaNeedsThis: "ASEAN is India's 4th largest trading partner; FTA deepens economic ties.",
    keyItems: ["Tariff liberalisation on 80% goods", "Rules of origin", "ASEAN market access"],
    date: "January 2010"
  },
  {
    title: "India–UK Free Trade Agreement Negotiations",
    country: "United Kingdom",
    value: "120B",
    status: "In Progress",
    type: "Trade",
    impact: "High Impact",
    description: "Ongoing bilateral FTA negotiations between India and the United Kingdom post-Brexit.",
    strategicIntent: "Unlock a major English-speaking market for Indian services and goods.",
    whyIndiaNeedsThis: "UK is top destination for Indian IT services and students; FTA would formalise and expand this.",
    keyItems: ["Services liberalisation", "Visa mobility for professionals", "Goods tariff reduction"],
    date: "2022"
  },
  {
    title: "India Semiconductor Mission – Micron, TATA, Foxconn MoUs",
    country: "USA",
    value: "21B",
    status: "In Progress",
    type: "Technology",
    impact: "High Impact",
    description: "Series of MoUs with Micron Technology, Tata Electronics, and Foxconn to establish semiconductor fabs in India.",
    strategicIntent: "Build India into a global semiconductor manufacturing hub and reduce import dependence.",
    whyIndiaNeedsThis: "India imports 100% of its chips; domestic fab capacity is a national security imperative.",
    keyItems: ["Micron ATMP facility in Sanand", "Tata-PSMC fab in Dholera", "Foxconn fab in Taloja"],
    date: "2023"
  },
  {
    title: "India–France Strategic Partnership (Enhanced Defence)",
    country: "France",
    value: "20B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Elevated India-France strategic partnership encompassing defence, space, nuclear, and critical technologies.",
    strategicIntent: "Build a multi-dimensional partnership with Europe's leading defence power.",
    whyIndiaNeedsThis: "France offers technology transfer that US and Russia often restrict.",
    keyItems: ["Rafale jets", "Scorpene submarines", "Space cooperation", "Nuclear cooperation"],
    date: "2023"
  },
  {
    title: "India–Egypt Strategic Partnership",
    country: "Egypt",
    value: "7B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "Elevation of India-Egypt ties to Strategic Partnership with focus on defence and trade.",
    strategicIntent: "Access African and Arab markets and build influence in North Africa.",
    whyIndiaNeedsThis: "Egypt controls the Suez Canal, critical for India's trade with Europe.",
    keyItems: ["Defence cooperation", "Pharma exports", "IT sector investment"],
    date: "2023"
  },
  {
    title: "India–Africa Defence Cooperation Initiative",
    country: "African Union",
    value: "0",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India-Africa defence partnership covering training, capacity building, and equipment supply.",
    strategicIntent: "Counter China's growing military presence in Africa and build South-South partnerships.",
    whyIndiaNeedsThis: "Africa hosts vital Indian Ocean littoral states; influence there secures maritime routes.",
    keyItems: ["Military training slots", "Lines of credit for defence", "Joint exercises"],
    date: "2020"
  },
  {
    title: "India–Greece Defence and Economic MoU",
    country: "Greece",
    value: "2B",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India and Greece signed defence and economic MoUs during PM Modi's visit to Athens.",
    strategicIntent: "Expand India's footprint in Mediterranean Europe and build EU strategic ties.",
    whyIndiaNeedsThis: "Greece is a NATO member and key maritime nation; partnership opens European door.",
    keyItems: ["Defence MoU", "Shipping cooperation", "Trade facilitation"],
    date: "August 2023"
  }
];