export const seedDeals = [
  // ─────────────────────────────────────────────
  // 1940s
  // ─────────────────────────────────────────────
  {
    title: "India–USA Grain Aid Agreement (PL-480)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "First major American food aid to newly independent India under Public Law 480, providing surplus wheat to address food scarcity.",
    strategicIntent: "Secure food supply for a newly independent nation facing famine conditions.",
    whyIndiaNeedsThis: "India faced acute food shortages post-partition and needed immediate grain imports.",
    keyItems: ["Wheat imports", "Concessional rupee payments", "Agricultural cooperation"],
    date: "1947"
  },
  {
    title: "Colombo Plan Membership",
    country: "United Kingdom",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India joined the Colombo Plan for cooperative economic and social development in Asia and the Pacific.",
    strategicIntent: "Access development aid and technical assistance from Commonwealth nations.",
    whyIndiaNeedsThis: "Framework for multilateral development cooperation for newly independent India.",
    keyItems: ["Technical assistance", "Capital aid", "Regional cooperation"],
    date: "1950"
  },
  {
    title: "India–UK Defence Supply Agreement (Post-Independence)",
    country: "United Kingdom",
    value: "0.2B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Britain continued supplying arms to newly independent India, including aircraft, ships, and small arms from existing colonial inventories.",
    strategicIntent: "Maintain military readiness in the immediate post-independence period.",
    whyIndiaNeedsThis: "India's armed forces inherited British equipment and needed spares, ammunition, and replacements.",
    keyItems: ["Spitfire aircraft", "Royal Navy vessels transfer", "Army small arms and artillery"],
    date: "1947"
  },
  {
    title: "India–Nepal Treaty of Peace and Friendship",
    country: "Nepal",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Foundational treaty governing India-Nepal relations, allowing free movement of citizens and goods between the two countries.",
    strategicIntent: "Secure the northern Himalayan frontier and maintain Nepal as a buffer state.",
    whyIndiaNeedsThis: "Open border and friendly Nepal is essential for India's security along the Tibetan frontier.",
    keyItems: ["Open border provisions", "Free movement of goods", "Mutual security cooperation"],
    date: "July 1950"
  },
  // ─────────────────────────────────────────────
  // 1950s
  // ─────────────────────────────────────────────
  {
    title: "India–USA Point Four Programme",
    country: "USA",
    value: "0.05B",
    status: "Completed",
    type: "Technology",
    impact: "Medium Impact",
    description: "Technical assistance agreement under President Truman's Point Four Programme for agricultural and industrial development.",
    strategicIntent: "Modernise Indian agriculture and industry through American technical know-how.",
    whyIndiaNeedsThis: "India needed technical expertise to build industrial and agricultural capacity from scratch.",
    keyItems: ["Agricultural extension programs", "Technical training", "Industrial demonstrations"],
    date: "1952"
  },
  {
    title: "India–Soviet Union Trade Agreement",
    country: "Russia",
    value: "0.1B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "First major trade agreement between India and the Soviet Union, establishing bilateral trade relations.",
    strategicIntent: "Diversify trade away from former colonial powers and build relations with socialist bloc.",
    whyIndiaNeedsThis: "Non-alignment policy required balancing trade between Western and Eastern blocs.",
    keyItems: ["Rupee-Ruble trade", "Machinery exports from USSR", "Indian cotton and textiles"],
    date: "1953"
  },
  {
    title: "Bhilai Steel Plant Agreement",
    country: "Russia",
    value: "0.15B",
    status: "Completed",
    type: "Technology",
    impact: "High Impact",
    description: "Soviet Union agreed to build the Bhilai Steel Plant in Chhattisgarh, India's first modern integrated steel plant.",
    strategicIntent: "Build India's heavy industrial base and reduce dependence on imports.",
    whyIndiaNeedsThis: "India's First Five Year Plan prioritised steel production for industrialisation.",
    keyItems: ["1 million ton steel plant", "Technology transfer", "Soviet technical experts"],
    date: "February 1955"
  },
  {
    title: "Rourkela Steel Plant (German Collaboration)",
    country: "Germany",
    value: "0.1B",
    status: "Completed",
    type: "Technology",
    impact: "High Impact",
    description: "West Germany agreed to build the Rourkela Steel Plant in Odisha as part of India's industrialisation drive.",
    strategicIntent: "Establish India's steel industry through foreign collaboration.",
    whyIndiaNeedsThis: "India needed multiple steel plants to meet growing demand and reduce imports.",
    keyItems: ["Steel plant construction", "German technology transfer", "Training of Indian engineers"],
    date: "1955"
  },
  {
    title: "Durgapur Steel Plant (British Collaboration)",
    country: "United Kingdom",
    value: "0.1B",
    status: "Completed",
    type: "Technology",
    impact: "High Impact",
    description: "UK agreed to build the Durgapur Steel Plant in West Bengal, part of the three-nation steel plant initiative.",
    strategicIntent: "Maintain Commonwealth ties while building domestic industrial capacity.",
    whyIndiaNeedsThis: "Three major steel plants were needed to feed India's Second Five Year Plan targets.",
    keyItems: ["Steel plant construction", "British Steelwork Associates involvement", "1 million ton capacity"],
    date: "1956"
  },
  {
    title: "India–USA Atomic Energy Agreement",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "Bilateral agreement for peaceful nuclear cooperation under the 'Atoms for Peace' programme.",
    strategicIntent: "Develop civilian nuclear energy capability to power India's growing economy.",
    whyIndiaNeedsThis: "India needed nuclear technology to develop an independent energy sector.",
    keyItems: ["Research reactor APSARA", "Nuclear fuel supply", "Technical training"],
    date: "August 1956"
  },
  {
    title: "CIRUS Research Reactor (Canadian Collaboration)",
    country: "Canada",
    value: "0",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "Canada supplied the CIRUS reactor to India under the Colombo Plan, a critical stepping stone in India's nuclear programme.",
    strategicIntent: "Develop indigenous nuclear research and energy capability.",
    whyIndiaNeedsThis: "India needed a research reactor to train nuclear scientists and generate plutonium.",
    keyItems: ["40 MW research reactor", "Heavy water supply", "Nuclear training"],
    date: "1956"
  },
  {
    title: "India–UK Hawker Hunter Aircraft Deal",
    country: "United Kingdom",
    value: "0.05B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India purchased Hawker Hunter fighter aircraft from the UK to modernise the Indian Air Force in the 1950s.",
    strategicIntent: "Equip IAF with modern subsonic jet fighters for air defence.",
    whyIndiaNeedsThis: "IAF needed to transition from propeller aircraft to jets to maintain regional air superiority.",
    keyItems: ["Hunter F56 aircraft", "Pilot training in UK", "Maintenance support"],
    date: "1957"
  },
  {
    title: "India–France Mystere IVA Fighter Deal",
    country: "France",
    value: "0.06B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India purchased Dassault Mystere IVA fighters from France, which later saw combat in the 1965 Indo-Pak War.",
    strategicIntent: "Diversify IAF's fighter fleet with a modern French design.",
    whyIndiaNeedsThis: "IAF needed a capable transonic fighter to balance against Pakistani Sabres.",
    keyItems: ["110 Mystere IVA aircraft", "French technical support", "Combat-proven design"],
    date: "1957"
  },
  {
    title: "Indus Waters Treaty",
    country: "Pakistan",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Water-distribution treaty brokered by the World Bank between India and Pakistan for the Indus river system.",
    strategicIntent: "Manage the use of the Indus River system's waters fairly between the two nations.",
    whyIndiaNeedsThis: "Ensured agricultural security for Punjab and Sindh regions via controlled river access.",
    keyItems: ["Allocation of Beas, Ravi, and Sutlej to India", "Allocation of Indus, Chenab, and Jhelum to Pakistan", "World Bank mediation"],
    date: "September 1960"
  },
  // ─────────────────────────────────────────────
  // 1960s
  // ─────────────────────────────────────────────
  {
    title: "India–Soviet MiG-21 License Production Agreement",
    country: "Russia",
    value: "0.3B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Landmark agreement for license production of MiG-21 fighter aircraft in India at HAL Nasik.",
    strategicIntent: "Build domestic fighter aircraft manufacturing capability and modernise IAF.",
    whyIndiaNeedsThis: "India needed modern supersonic fighters and indigenous production capability after 1962 war.",
    keyItems: ["MiG-21 aircraft", "License production at HAL", "Technology transfer"],
    date: "1962"
  },
  {
    title: "India–USA Tarapur Nuclear Power Agreement",
    country: "USA",
    value: "0.08B",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "Agreement for the US to build India's first nuclear power plant at Tarapur, Maharashtra.",
    strategicIntent: "Develop civilian nuclear power generation capacity in India.",
    whyIndiaNeedsThis: "India needed nuclear power plants to meet growing electricity demand.",
    keyItems: ["Two 200 MW BWR reactors", "US fuel supply commitment", "Training of Indian nuclear engineers"],
    date: "1963"
  },
  {
    title: "India–Soviet AN-12 Transport Aircraft Deal",
    country: "Russia",
    value: "0.05B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India acquired AN-12 military transport aircraft from the Soviet Union to expand IAF's airlift capability.",
    strategicIntent: "Build strategic airlift for troops and supplies across difficult Himalayan terrain.",
    whyIndiaNeedsThis: "Post-1962 war, India urgently needed to improve its ability to supply remote border areas.",
    keyItems: ["AN-12 transport aircraft", "Crew training", "Cargo and troop transport"],
    date: "1963"
  },
  {
    title: "India–UK INS Vikrant Aircraft Carrier Acquisition",
    country: "United Kingdom",
    value: "0.12B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India acquired the Majestic-class carrier HMS Hercules from the UK, commissioned as INS Vikrant, India's first aircraft carrier.",
    strategicIntent: "Project naval power in the Indian Ocean and establish carrier aviation capability.",
    whyIndiaNeedsThis: "India needed an aircraft carrier to dominate the Indian Ocean and protect sea lanes.",
    keyItems: ["CATOBAR carrier", "Sea Hawk fighters", "Naval aviation training"],
    date: "1961"
  },
  {
    title: "India–France Alouette III Helicopter Deal",
    country: "France",
    value: "0.03B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India acquired Alouette III helicopters from France with license production at HAL Bangalore.",
    strategicIntent: "Provide mountain warfare and utility helicopter capability to Indian armed forces.",
    whyIndiaNeedsThis: "Post-1962 war, high-altitude helicopter capability was a critical gap to fill.",
    keyItems: ["Alouette III helicopters", "License production at HAL", "High-altitude operations"],
    date: "1965"
  },
  {
    title: "Indo–Soviet Treaty of Peace, Friendship and Cooperation",
    country: "Russia",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "20-year treaty of friendship between India and the Soviet Union, providing Soviet backing in case of external aggression.",
    strategicIntent: "Secure a strategic partner during the 1971 Bangladesh War and counter US-China-Pakistan alliance.",
    whyIndiaNeedsThis: "India needed diplomatic cover during the 1971 Bangladesh Liberation War.",
    keyItems: ["Mutual consultation clause", "Soviet naval deployment deterrence", "Arms supply guarantee"],
    date: "August 1971"
  },
  {
    title: "India–Soviet Arms Supply Agreement (1971 War)",
    country: "Russia",
    value: "0.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Emergency arms supply by USSR to India during 1971 Indo-Pak War including tanks, aircraft, and naval vessels.",
    strategicIntent: "Ensure decisive military victory and creation of Bangladesh.",
    whyIndiaNeedsThis: "India needed rapid arms resupply to sustain a two-front war against Pakistan.",
    keyItems: ["T-55 tanks", "Aircraft ammunition", "Naval vessels"],
    date: "December 1971"
  },
  // ─────────────────────────────────────────────
  // 1970s
  // ─────────────────────────────────────────────
  {
    title: "India–UK Jaguar Aircraft Deal",
    country: "United Kingdom",
    value: "1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased Jaguar strike aircraft from the UK/France SEPECAT consortium and licensed HAL to produce them.",
    strategicIntent: "Replace ageing Canberra bombers and provide deep-strike capability to IAF.",
    whyIndiaNeedsThis: "IAF needed a modern ground-attack aircraft after 1971 war experience.",
    keyItems: ["120 Jaguar aircraft", "HAL license production", "Adour engine manufacturing"],
    date: "1978"
  },
  {
    title: "India–Soviet T-72 Tank License Production Deal",
    country: "Russia",
    value: "0.4B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India licensed the T-72 main battle tank from the Soviet Union with production at Heavy Vehicles Factory, Avadi.",
    strategicIntent: "Modernise Indian Army's armoured forces with second-generation main battle tanks.",
    whyIndiaNeedsThis: "Indian Army needed to replace ageing Centurion tanks with modern MBTs for Pakistan and China fronts.",
    keyItems: ["T-72 Ajeya tanks", "License production at HVF Avadi", "Technology transfer"],
    date: "1980"
  },
  {
    title: "India–Soviet Kilo Class Submarine Deal",
    country: "Russia",
    value: "0.8B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India acquired Kilo-class diesel-electric submarines from the Soviet Union to build undersea warfare capability.",
    strategicIntent: "Develop India's submarine fleet and underwater warfare capability in the Indian Ocean.",
    whyIndiaNeedsThis: "IN had limited submarine capability; Kilo class gave it blue-water deterrence.",
    keyItems: ["10 Kilo-class submarines", "Submarine crew training", "Maintenance support"],
    date: "1980"
  },
  // ─────────────────────────────────────────────
  // 1980s
  // ─────────────────────────────────────────────
  {
    title: "India–Soviet INS Chakra (Charlie-I) Lease",
    country: "Russia",
    value: "0",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India leased a Soviet Charlie-I class nuclear-powered submarine, becoming the sixth nation to operate a nuclear submarine.",
    strategicIntent: "Train Indian Navy crew on nuclear submarine operations and demonstrate blue-water capability.",
    whyIndiaNeedsThis: "India needed nuclear submarine operating experience for its future ATV (Arihant) programme.",
    keyItems: ["Charlie-I SSGN", "3-year lease", "Crew training"],
    date: "January 1988"
  },
  {
    title: "India–France Mirage 2000 Deal",
    country: "France",
    value: "2.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased Mirage 2000 multi-role fighters from France, which later played a decisive role in the Kargil War.",
    strategicIntent: "Acquire advanced multi-role combat aircraft with beyond-visual-range capability.",
    whyIndiaNeedsThis: "IAF needed modern 4th-gen fighters as the MiG-21 fleet was ageing.",
    keyItems: ["36 Mirage 2000H/TH aircraft", "SNECMA M53 engines", "Magic and Super 530D missiles"],
    date: "1982"
  },
  {
    title: "India–Soviet MiG-29 Fighter Deal",
    country: "Russia",
    value: "0.6B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India acquired MiG-29 Fulcrum air superiority fighters from the Soviet Union, a significant jump in IAF capability.",
    strategicIntent: "Counter Pakistani F-16s and achieve air superiority over the subcontinent.",
    whyIndiaNeedsThis: "Pakistan's F-16 acquisition forced India to seek a comparable BVR-capable fighter urgently.",
    keyItems: ["44 MiG-29B aircraft", "R-60 and R-27 missiles", "IRST and radar systems"],
    date: "1984"
  },
  {
    title: "India–West Germany HDW Submarine Deal",
    country: "Germany",
    value: "0.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India contracted Howaldtswerke-Deutsche Werft (HDW) for four Type 1500 submarines with two built in Germany and two at MDL Mumbai.",
    strategicIntent: "Expand submarine fleet and build domestic submarine construction expertise.",
    whyIndiaNeedsThis: "India needed conventional submarines to secure the Indian Ocean against Pakistani and Chinese threats.",
    keyItems: ["2 submarines built in Germany", "2 built at MDL Mumbai", "Technology transfer"],
    date: "1981"
  },
  {
    title: "India–Soviet Ilyushin IL-76 Transport Deal",
    country: "Russia",
    value: "0.2B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India acquired IL-76 heavy strategic transport aircraft from the Soviet Union for the Indian Air Force.",
    strategicIntent: "Build heavy strategic airlift capability for troops and equipment over long distances.",
    whyIndiaNeedsThis: "IAF needed heavy-lift aircraft for rapid deployment and humanitarian operations.",
    keyItems: ["IL-76 Candid aircraft", "Cargo and troop transport", "Air refuelling tanker conversion"],
    date: "1985"
  },
  // ─────────────────────────────────────────────
  // 1990s
  // ─────────────────────────────────────────────
  {
    title: "BrahMos Cruise Missile Joint Development",
    country: "Russia",
    value: "0.5B",
    status: "Ongoing",
    type: "Technology",
    impact: "High Impact",
    description: "A joint venture between India's DRDO and Russia's NPO Mashinostroyenia to develop the BrahMos supersonic cruise missile.",
    strategicIntent: "Develop world's fastest supersonic cruise missile for land, sea, and air platforms.",
    whyIndiaNeedsThis: "Enhance precision strike capability and maritime dominance in the Indian Ocean.",
    keyItems: ["Propulsion technology", "Missile airframes", "Joint marketing and export"],
    date: "February 1998"
  },
  {
    title: "India–WTO Membership",
    country: "Multilateral",
    value: "0",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "India became a founding member of the World Trade Organization, replacing the GATT framework.",
    strategicIntent: "Integrate India into the global rules-based trading order and protect Indian trade interests.",
    whyIndiaNeedsThis: "WTO membership gave India formal multilateral dispute settlement and market access rights.",
    keyItems: ["Tariff bindings", "TRIPS compliance", "Dispute settlement access"],
    date: "January 1995"
  },
  {
    title: "India–USA General Electric F404 Engine Deal (LCA Tejas)",
    country: "USA",
    value: "0.1B",
    status: "Completed",
    type: "Technology",
    impact: "Medium Impact",
    description: "India procured GE F404 turbofan engines from the USA to power the indigenous Light Combat Aircraft (LCA) Tejas.",
    strategicIntent: "Overcome engine development bottleneck and keep India's LCA programme on track.",
    whyIndiaNeedsThis: "India's indigenous Kaveri engine programme was delayed; a foreign engine kept Tejas flying.",
    keyItems: ["GE F404-GE-F2J3 engines", "Technology co-development terms", "HAL integration work"],
    date: "1998"
  },
  {
    title: "India–Russia T-90 Tank Purchase",
    country: "Russia",
    value: "1.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased T-90S Bhishma main battle tanks from Russia with license production at Heavy Vehicles Factory, Avadi.",
    strategicIntent: "Equip Indian Army with third-generation MBTs with composite armour and night-fighting capability.",
    whyIndiaNeedsThis: "Indian Army needed modern tanks with reactive armour to counter Pakistani and Chinese armour.",
    keyItems: ["Over 1,000 T-90S tanks", "License production at HVF Avadi", "Kontakt-5 reactive armour"],
    date: "2001"
  },
  {
    title: "India–Israel Heron Drone Deal",
    country: "Israel",
    value: "0.25B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India acquired Israeli Heron medium-altitude long-endurance UAVs for ISR missions across all three services.",
    strategicIntent: "Build persistent surveillance capability over borders and maritime zones.",
    whyIndiaNeedsThis: "India lacked long-endurance UAVs for monitoring Pakistan and China borders and the IOR.",
    keyItems: ["Heron MALE UAVs", "Satellite data links", "ISR sensors package"],
    date: "1999"
  },
  // ─────────────────────────────────────────────
  // 2000s
  // ─────────────────────────────────────────────
  {
    title: "India–Russia Admiral Gorshkov (INS Vikramaditya) Aircraft Carrier Deal",
    country: "Russia",
    value: "2.9B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India acquired and refurbished the Kiev-class carrier Admiral Gorshkov from Russia, renamed INS Vikramaditya.",
    strategicIntent: "Maintain carrier aviation capability after decommissioning of INS Viraat.",
    whyIndiaNeedsThis: "India needed a carrier to project power in the Indian Ocean and train naval aviators.",
    keyItems: ["45,000-ton carrier", "MiG-29K aircraft package", "Extensive refit at Sevmash"],
    date: "2004"
  },
  {
    title: "India–USA Civil Nuclear Deal (123 Agreement)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "The historic framework for civil nuclear cooperation, lifting the global nuclear trade embargo on India.",
    strategicIntent: "Secure reliable energy sources for India's growing economy while gaining de facto recognition as a nuclear power.",
    whyIndiaNeedsThis: "India was isolated from global nuclear technology since 1974; this deal allowed import of uranium and reactors.",
    keyItems: ["Separation of civil and military nuclear facilities", "IAEA safeguards compliance", "Access to US nuclear technology"],
    date: "October 2008"
  },
  {
    title: "India–Russia MiG-29K Naval Fighter Deal",
    country: "Russia",
    value: "1.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased MiG-29K/KUB carrier-borne fighters for INS Vikramaditya and future INS Vikrant.",
    strategicIntent: "Provide carrier aviation strike and fleet air defence capability to the Indian Navy.",
    whyIndiaNeedsThis: "India's carrier air wing needed a modern supersonic fighter to replace the Sea Harrier.",
    keyItems: ["45 MiG-29K/KUB aircraft", "Training simulators", "Full support package"],
    date: "2004"
  },
  {
    title: "India–Israel Phalcon AWACS Deal",
    country: "Israel",
    value: "1.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India acquired three Phalcon Airborne Warning and Control System aircraft mounted on Russian IL-76 platforms.",
    strategicIntent: "Provide India with advanced airborne surveillance and battle management capability.",
    whyIndiaNeedsThis: "IAF needed AEW&C capability to monitor large airspace during conflicts.",
    keyItems: ["3 Phalcon AWACS", "ELM-2075 radar", "Datalink integration with IAF fighters"],
    date: "2004"
  },
  {
    title: "India–France Scorpene Submarine Deal",
    country: "France",
    value: "3.75B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India contracted DCNS (now Naval Group) to build six Scorpene-class diesel-electric submarines at Mazagon Dock, Mumbai.",
    strategicIntent: "Expand India's conventional submarine fleet and build undersea manufacturing capability.",
    whyIndiaNeedsThis: "India's submarine fleet was ageing; new boats were critical for underwater deterrence.",
    keyItems: ["6 Scorpene submarines", "Technology transfer to MDL", "AIP system for future boats"],
    date: "October 2005"
  },
  {
    title: "India–USA NSSP and Defence Cooperation Agreement",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Next Steps in Strategic Partnership and formal defence cooperation framework between India and the USA.",
    strategicIntent: "Transform India-US relationship from transactional to strategic and defence partnership.",
    whyIndiaNeedsThis: "India needed US cooperation in high-tech areas including space, nuclear, and defence.",
    keyItems: ["Defence technology transfer", "Space cooperation", "Civil nuclear pathway"],
    date: "2005"
  },
  {
    title: "India–Afghanistan Strategic Partnership Agreement",
    country: "Afghanistan",
    value: "2B",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "India signed its first strategic partnership agreement with Afghanistan, pledging development and security assistance.",
    strategicIntent: "Build influence in Afghanistan, counter Pakistani proxy strategies, and secure regional stability.",
    whyIndiaNeedsThis: "A stable Afghanistan serves India's strategic depth and trade corridor interests.",
    keyItems: ["Parliament building construction", "Salma Dam (Afghan-India Friendship Dam)", "Zaranj-Delaram highway"],
    date: "2011"
  },
  {
    title: "India–Israel Harop Loitering Munition Deal",
    country: "Israel",
    value: "0.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India acquired Harop anti-radiation loitering munitions from Israel for suppression of enemy air defences.",
    strategicIntent: "Provide IAF with a standoff SEAD capability to destroy enemy radar and SAM systems.",
    whyIndiaNeedsThis: "India needed a drone-based SEAD capability to suppress Pakistani and Chinese air defence networks.",
    keyItems: ["Harop loitering munitions", "Anti-radiation homing", "SEAD capability"],
    date: "2009"
  },
  {
    title: "India–Russia INS Chakra-II Lease Agreement",
    country: "Russia",
    value: "0.9B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India leased Akula-II class nuclear submarine INS Chakra from Russia for 10 years.",
    strategicIntent: "Maintain nuclear submarine operating experience while Arihant class was under construction.",
    whyIndiaNeedsThis: "India needed continuous nuclear submarine operations training.",
    keyItems: ["Akula-II class SSGN", "10-year lease", "Nuclear propulsion training"],
    date: "2012"
  },
  {
    title: "India–Japan CEPA (Comprehensive Economic Partnership Agreement)",
    country: "Japan",
    value: "15B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "Comprehensive Economic Partnership Agreement between India and Japan covering trade in goods, services, and investment.",
    strategicIntent: "Boost bilateral trade, attract Japanese investment, and integrate supply chains.",
    whyIndiaNeedsThis: "Japan was India's top infrastructure and FDI partner; a CEPA formalised and deepened the relationship.",
    keyItems: ["Tariff reduction on 90% goods", "Investment promotion", "Services liberalisation"],
    date: "August 2011"
  },
  {
    title: "India–South Korea CEPA",
    country: "South Korea",
    value: "12B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "Comprehensive Economic Partnership Agreement between India and South Korea.",
    strategicIntent: "Expand trade in electronics, automotive, and pharmaceuticals.",
    whyIndiaNeedsThis: "Korea offered tech transfer and FDI in manufacturing sectors India needed to develop.",
    keyItems: ["Tariff concessions", "Investment facilitation", "Technology collaboration"],
    date: "January 2010"
  },
  {
    title: "India–USA C-17 Globemaster III Transport Aircraft Deal",
    country: "USA",
    value: "4.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased 10 C-17 Globemaster III strategic airlift aircraft from Boeing for the Indian Air Force.",
    strategicIntent: "Build strategic airlift capability for rapid troop and equipment deployment across India and abroad.",
    whyIndiaNeedsThis: "IAF needed heavy strategic transport aircraft for operations in high-altitude areas and disaster relief.",
    keyItems: ["10 C-17 aircraft", "Strategic airlift capability", "Humanitarian assistance role"],
    date: "2011"
  },
  {
    title: "India–USA P-8I Poseidon Maritime Patrol Aircraft Deal",
    country: "USA",
    value: "2.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased Boeing P-8I Poseidon maritime patrol and ASW aircraft for the Indian Navy.",
    strategicIntent: "Dominate the Indian Ocean with advanced sub-hunting and maritime surveillance capability.",
    whyIndiaNeedsThis: "China's expanding submarine operations in the Indian Ocean required superior ASW capability.",
    keyItems: ["12 P-8I aircraft", "Harpoon missiles", "Sonobuoy systems"],
    date: "2009"
  },
  {
    title: "India–Israel Barak-8 Missile System Deal",
    country: "Israel",
    value: "2B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Joint India-Israel development and procurement of the Barak-8 medium-range surface-to-air missile system.",
    strategicIntent: "Provide naval and land-based air defence against aircraft, missiles, and drones.",
    whyIndiaNeedsThis: "India needed modern SAM systems for naval vessels and land forces.",
    keyItems: ["Barak-8 missiles", "MRSAM land version", "Joint production by DRDO and IAI"],
    date: "2009"
  },
  {
    title: "India–France Rafale Fighter Jet Deal (36 Aircraft)",
    country: "France",
    value: "8.7B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased 36 Rafale multi-role combat aircraft from France in a government-to-government deal. All 36 jets were delivered by December 2022.",
    strategicIntent: "Rapidly bridge IAF's combat capability gap with a battle-proven 4.5-gen fighter.",
    whyIndiaNeedsThis: "IAF was down to 30 squadrons against a required 42; Rafale was the quickest solution.",
    keyItems: ["36 Rafale F3R jets", "Meteor BVR missiles", "SCALP cruise missiles", "India-specific enhancements"],
    date: "September 2016"
  },
  {
    title: "India–USA COMCASA (Communications Compatibility and Security Agreement)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "India signed the Communications Compatibility and Security Agreement with the USA enabling encrypted military communications.",
    strategicIntent: "Enable real-time data sharing between Indian and US military platforms.",
    whyIndiaNeedsThis: "India could not receive encrypted communications with US-origin systems without COMCASA.",
    keyItems: ["Encrypted comms capability", "US platform data links", "Interoperability with US forces"],
    date: "September 2018"
  },
  {
    title: "India–Russia S-400 Triumf Missile System Purchase",
    country: "Russia",
    value: "5.4B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Contract for five squadrons of the S-400 long-range air defence missile system.",
    strategicIntent: "Provide a long-range surface-to-air missile shield for major cities and strategic assets.",
    whyIndiaNeedsThis: "Counter threats from advanced aerial platforms and ballistic missiles along long border stretches.",
    keyItems: ["5 S-400 Regiments", "Command and Control centers", "Radar systems"],
    date: "October 2018"
  },
  {
    title: "India–USA BECA (Basic Exchange and Cooperation Agreement)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "India signed the Basic Exchange and Cooperation Agreement enabling sharing of geospatial intelligence and maps.",
    strategicIntent: "Enhance precision targeting and navigation for Indian missiles and military systems.",
    whyIndiaNeedsThis: "Indian missiles and aircraft would gain GPS-accuracy using US geospatial data.",
    keyItems: ["Geospatial intelligence sharing", "Precision navigation data", "Topographic mapping"],
    date: "October 2020"
  },
  {
    title: "India–USA LEMOA (Logistics Exchange Memorandum of Agreement)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "India signed the Logistics Exchange MOU with the USA allowing mutual use of military facilities for logistics.",
    strategicIntent: "Enable Indian and US forces to resupply and refuel at each other's bases globally.",
    whyIndiaNeedsThis: "India needed logistics support for long-range operations and disaster relief missions.",
    keyItems: ["Mutual base access", "Fuel and logistics sharing", "Navy port calls"],
    date: "August 2016"
  },
  {
    title: "India–Israel Defense Trade and R&D Partnership",
    country: "Israel",
    value: "5B",
    status: "Ongoing",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "Broad defence partnership making Israel one of India's top arms suppliers including drones, missiles, and electronics.",
    strategicIntent: "Access cutting-edge Israeli drone, missile, and electronic warfare technology.",
    whyIndiaNeedsThis: "Israeli systems like Heron drones and Barak missiles filled critical IAF/IN capability gaps.",
    keyItems: ["Heron drones", "Harop loitering munitions", "EW systems", "Spike ATGMs"],
    date: "2000"
  },
  {
    title: "India–Japan Special Strategic and Global Partnership",
    country: "Japan",
    value: "35B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Elevation of India-Japan ties to Special Strategic and Global Partnership including bullet train, infrastructure, and defence cooperation.",
    strategicIntent: "Counter China's influence with a like-minded democratic partner.",
    whyIndiaNeedsThis: "Japan's capital and technology are vital for India's smart cities, bullet train, and digital infrastructure.",
    keyItems: ["Mumbai-Ahmedabad bullet train", "JPY 50,000 crore ODA", "Defence technology cooperation"],
    date: "2014"
  },
  // ─────────────────────────────────────────────
  // 2010s
  // ─────────────────────────────────────────────
  {
    title: "India–UAE Comprehensive Economic Partnership Agreement",
    country: "UAE",
    value: "100B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "First bilateral free trade agreement signed by India in a decade, with UAE being India's second largest trading partner.",
    strategicIntent: "Boost bilateral trade, remittances, and investment from Gulf region.",
    whyIndiaNeedsThis: "UAE hosts 3.5 million Indian diaspora and is India's gateway to Gulf trade.",
    keyItems: ["Zero tariff on 80% Indian goods", "Investment facilitation", "Services liberalisation"],
    date: "May 2022"
  },
  {
    title: "India–Australia ECTA (Economic Cooperation and Trade Agreement)",
    country: "Australia",
    value: "45B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "Interim free trade agreement between India and Australia covering goods, services, and investment.",
    strategicIntent: "Deepen trade ties with a key Quad partner and diversify supply chains.",
    whyIndiaNeedsThis: "Australia supplies critical minerals, education, and commodities India needs.",
    keyItems: ["Zero duty on Australian coal, sheep meat, wool", "Duty-free Indian textiles and pharma", "Critical minerals cooperation"],
    date: "December 2022"
  },
  {
    title: "India–GCC Free Trade Agreement Negotiations",
    country: "Saudi Arabia",
    value: "0",
    status: "Proposed",
    type: "Trade",
    impact: "High Impact",
    description: "Ongoing negotiations for a free trade agreement between India and the Gulf Cooperation Council.",
    strategicIntent: "Secure India's largest trade partner region in a formal trade framework.",
    whyIndiaNeedsThis: "Gulf countries are India's largest oil suppliers and host 9 million Indian workers.",
    keyItems: ["Tariff reduction on Indian goods", "Services liberalisation", "Investment protection"],
    date: "2023"
  },
  {
    title: "India–USA C-130J Super Hercules Transport Deal",
    country: "USA",
    value: "1.2B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India purchased C-130J Super Hercules tactical transport aircraft for special operations and mountain supply missions.",
    strategicIntent: "Build tactical airlift capability for special forces and supply of high-altitude border posts.",
    whyIndiaNeedsThis: "IAF needed a modern tactical airlifter for Siachen glacier, Ladakh, and Northeast India operations.",
    keyItems: ["6 C-130J aircraft", "Special operations configuration", "High-altitude landing capability"],
    date: "2008"
  },
  {
    title: "India–USA Apache Attack Helicopter Deal",
    country: "USA",
    value: "1.4B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India purchased AH-64E Apache attack helicopters from Boeing for the Indian Army and Air Force.",
    strategicIntent: "Provide cutting-edge anti-armour and close air support capability.",
    whyIndiaNeedsThis: "India needed modern attack helicopters to counter massed armour on the plains and in mountains.",
    keyItems: ["22 AH-64E Apaches", "Hellfire Longbow missiles", "Night-fighting sensors"],
    date: "2015"
  },
  {
    title: "India–USA Chinook Heavy Lift Helicopter Deal",
    country: "USA",
    value: "1.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India purchased CH-47F Chinook heavy-lift helicopters from Boeing for the Indian Air Force.",
    strategicIntent: "Build heavy-lift helicopter capability for mountain warfare and disaster relief.",
    whyIndiaNeedsThis: "IAF needed to replace ageing Mi-26 heavy-lift helicopters for Siachen and Northeast supply.",
    keyItems: ["15 CH-47F Chinooks", "Heavy-lift capability", "Mountain operations configuration"],
    date: "2015"
  },
  {
    title: "India–Russia Kamov Ka-226T Helicopter Deal",
    country: "Russia",
    value: "1B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India and Russia signed a deal for 200 Ka-226T light utility helicopters with production at HAL under Make in India.",
    strategicIntent: "Replace ageing Cheetah and Chetak helicopters in all three services.",
    whyIndiaNeedsThis: "India's light helicopter fleet was dangerously outdated; high-altitude variants were critical.",
    keyItems: ["200 Ka-226T helicopters", "60% indigenous content", "HAL production line"],
    date: "2015"
  },
  {
    title: "India–Israel Spike Anti-Tank Missile Deal",
    country: "Israel",
    value: "0.5B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India purchased Spike NLOS and Spike MR anti-tank guided missiles from Rafael of Israel for the Indian Army.",
    strategicIntent: "Provide infantry and mechanised forces with modern man-portable anti-armour capability.",
    whyIndiaNeedsThis: "India's Milan ATGMs were outdated; Spike offered longer range and fire-and-forget capability.",
    keyItems: ["Spike MR and NLOS missiles", "Man-portable launchers", "Fire-and-forget guidance"],
    date: "2021"
  },
  // ─────────────────────────────────────────────
  // 2020s
  // ─────────────────────────────────────────────
  {
    title: "India–USA iCET (Initiative on Critical and Emerging Technologies)",
    country: "USA",
    value: "0",
    status: "Ongoing",
    type: "Technology",
    impact: "High Impact",
    description: "Landmark initiative for co-development of critical technologies including semiconductors, AI, quantum computing, and defence.",
    strategicIntent: "Build technological self-reliance with US partnership in cutting-edge sectors.",
    whyIndiaNeedsThis: "India needs access to US tech ecosystem to achieve technological leadership.",
    keyItems: ["Semiconductor ecosystem", "AI and quantum computing", "GE F414 engine co-production for Tejas Mk2"],
    date: "January 2023"
  },
  {
    title: "India–USA GE F414 Engine Deal for Tejas Mk2",
    country: "USA",
    value: "0.7B",
    status: "In Progress",
    type: "Technology",
    impact: "High Impact",
    description: "USA agreed to transfer 80% technology for GE F414 turbofan engines to India for production at HAL.",
    strategicIntent: "Achieve strategic engine manufacturing capability and power the Tejas Mk2 fighter.",
    whyIndiaNeedsThis: "India's Kaveri engine programme remains incomplete; F414 production will bridge the gap.",
    keyItems: ["F414 engine production at HAL", "80% technology transfer", "200 engines for Tejas Mk2"],
    date: "2023"
  },
  {
    title: "India–USA MQ-9B Predator Drone Deal",
    country: "USA",
    value: "3.07B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India to purchase 31 MQ-9B SeaGuardian and SkyGuardian armed drones from General Atomics for tri-services.",
    strategicIntent: "Provide India with persistent ISR and armed strike capability over land and sea.",
    whyIndiaNeedsThis: "India needs long-endurance armed drones to monitor Chinese build-up along LAC and in IOR.",
    keyItems: ["15 SeaGuardian for Navy", "8 for Army", "8 for IAF", "Hellfire missiles"],
    date: "2023"
  },
  {
    title: "India–Russia INS Chakra-III Nuclear Submarine Lease",
    country: "Russia",
    value: "3B",
    status: "Proposed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India is negotiating lease of a third nuclear-powered attack submarine from Russia.",
    strategicIntent: "Maintain nuclear undersea deterrence while domestic Arihant-class SSBNs are under construction.",
    whyIndiaNeedsThis: "India needs SSN capability to counter China's growing submarine fleet in the IOR.",
    keyItems: ["Akula-II class SSN", "10-year lease", "Crew training"],
    date: "2024"
  },
  {
    title: "114 Rafale MRFA Deal (Multi-Role Fighter Aircraft)",
    country: "France",
    value: "40B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India's cabinet approved a massive ~$40B deal for 114 Rafale MRFA jets to replace ageing MiG-21 and Jaguar fleets. This is completely separate from the 36-jet 2016 deal which is already completed.",
    strategicIntent: "Modernise IAF combat fleet, achieve 42-squadron strength, and build fighter jet manufacturing capability domestically.",
    whyIndiaNeedsThis: "IAF currently has only 30 squadrons against required 42. MiG-21s are being phased out; India needs advanced MRCA jets urgently.",
    keyItems: ["114 Rafale jets (18 fly-away, 96 built in India)", "Technology Transfer to HAL", "Meteor, MICA, SCALP missiles"],
    date: "February 2025"
  },
  {
    title: "India–European Union Free Trade Agreement",
    country: "European Union",
    value: "500B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "A comprehensive free trade agreement concluded between India and the European Union on January 27, 2026 after nearly two decades of negotiations.",
    strategicIntent: "Open EU's $17 trillion market to Indian goods and services, and attract European investment.",
    whyIndiaNeedsThis: "EU is India's largest trading bloc; an FTA removes tariffs on Indian pharma, textiles, and IT services.",
    keyItems: ["Tariff elimination on goods", "Services market access", "Investment liberalisation", "Dispute settlement mechanism"],
    date: "January 2026"
  },
  {
    title: "India–Quad Security Framework",
    country: "USA",
    value: "0",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Quadrilateral Security Dialogue between India, USA, Japan, and Australia for a free and open Indo-Pacific.",
    strategicIntent: "Counter Chinese military and economic assertiveness in the Indo-Pacific.",
    whyIndiaNeedsThis: "India needs multilateral backing to balance against Chinese threats across LAC and IOR.",
    keyItems: ["Joint naval exercises (Malabar)", "Vaccine and technology initiatives", "Critical infrastructure protection"],
    date: "2021"
  },
  {
    title: "India–Maldives Development Partnership",
    country: "Maldives",
    value: "1.4B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India's development assistance to Maldives including infrastructure, health, and connectivity projects.",
    strategicIntent: "Maintain strategic influence in the Indian Ocean island nation and counter Chinese infrastructure investments.",
    whyIndiaNeedsThis: "Maldives sits astride key shipping lanes; Indian influence ensures IOR stability.",
    keyItems: ["Greater Male Connectivity Project", "Health sector support", "Airport development"],
    date: "2020"
  },
  {
    title: "India–Sri Lanka Economic Cooperation",
    country: "Sri Lanka",
    value: "4B",
    status: "Ongoing",
    type: "Trade",
    impact: "Medium Impact",
    description: "Comprehensive assistance package during Sri Lanka's economic crisis and long-term development cooperation.",
    strategicIntent: "Maintain strategic neighbourhood influence and counter China's debt-trap diplomacy.",
    whyIndiaNeedsThis: "Sri Lanka is critical to India's southern maritime security and Indian Ocean strategy.",
    keyItems: ["Currency swap lines", "Fuel supply", "Trincomalee energy zone development"],
    date: "2022"
  },
  {
    title: "India–Bangladesh Teesta Water Treaty (Pending)",
    country: "Bangladesh",
    value: "0",
    status: "Proposed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Long-pending agreement for equitable distribution of Teesta river waters between India and Bangladesh.",
    strategicIntent: "Cement bilateral ties with Bangladesh and address a major source of friction.",
    whyIndiaNeedsThis: "Bangladesh is India's largest trade partner in South Asia; resolving Teesta will deepen ties.",
    keyItems: ["Water sharing formula", "Joint river commission", "Agricultural cooperation"],
    date: "Pending"
  },
  {
    title: "India–Nepal Power Trade Agreement",
    country: "Nepal",
    value: "5B",
    status: "Ongoing",
    type: "Energy",
    impact: "High Impact",
    description: "India agreed to purchase 10,000 MW of hydroelectric power from Nepal over 10 years.",
    strategicIntent: "Meet India's growing power needs from clean energy and integrate Nepal economically.",
    whyIndiaNeedsThis: "Nepal's vast hydro potential can power India's northern states sustainably.",
    keyItems: ["10,000 MW hydro power purchase", "Cross-border transmission lines", "Joint project development"],
    date: "2023"
  },
  {
    title: "India–Saudi Arabia Strategic Partnership Council",
    country: "Saudi Arabia",
    value: "75B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Comprehensive strategic partnership including energy, defence, investment, and cultural ties.",
    strategicIntent: "Secure oil supply, attract Gulf investments, and deepen ties with the Arab world's largest economy.",
    whyIndiaNeedsThis: "Saudi Arabia is India's top oil supplier and home to 2.5 million Indian workers.",
    keyItems: ["$75B investment pledge", "Oil supply security", "Defence cooperation", "UPI payment interoperability"],
    date: "2019"
  },
  {
    title: "India–China Border Trade Agreements",
    country: "China",
    value: "0",
    status: "Completed",
    type: "Trade",
    impact: "Medium Impact",
    description: "Series of agreements on border trade including Nathula Pass reopening and border haats.",
    strategicIntent: "Manage economic relations with China despite political tensions.",
    whyIndiaNeedsThis: "China is India's largest trading partner; managing border trade reduces friction.",
    keyItems: ["Nathula Pass trade route", "Border haats in Northeast", "Trade facilitation measures"],
    date: "2006"
  },
  {
    title: "India–Israel Free Trade Agreement Negotiations",
    country: "Israel",
    value: "10B",
    status: "In Progress",
    type: "Trade",
    impact: "Medium Impact",
    description: "Ongoing negotiations for a free trade agreement between India and Israel.",
    strategicIntent: "Formalise trade and technology ties with Israel beyond defence cooperation.",
    whyIndiaNeedsThis: "Israel offers agri-tech, water tech, and cybersecurity expertise India urgently needs.",
    keyItems: ["Technology trade liberalisation", "Agri-tech cooperation", "Pharma market access"],
    date: "2022"
  },
  {
    title: "India–Canada Potash Import Agreement",
    country: "Canada",
    value: "0.5B",
    status: "Ongoing",
    type: "Trade",
    impact: "Medium Impact",
    description: "Long-term agreements for India to import potash fertiliser from Canada.",
    strategicIntent: "Secure fertiliser supplies for Indian agriculture.",
    whyIndiaNeedsThis: "India imports 90% of its potash; Canada is the world's largest producer.",
    keyItems: ["Potash supply agreements", "Competitive pricing", "Agricultural cooperation"],
    date: "2000"
  },
  {
    title: "India–Russia Oil Purchase Agreements (Post-Ukraine)",
    country: "Russia",
    value: "50B",
    status: "Ongoing",
    type: "Trade",
    impact: "High Impact",
    description: "India massively scaled up discounted crude oil imports from Russia following Western sanctions post-Ukraine war.",
    strategicIntent: "Secure cheap oil to manage inflation and reduce India's energy import bill.",
    whyIndiaNeedsThis: "Russian crude at $20-30 discounts to Brent saved India billions in forex outgo.",
    keyItems: ["Discounted crude oil", "Rupee-Ruble payment mechanism", "Refinery upgrades for Urals crude"],
    date: "2022"
  },
  {
    title: "India–Iran Chabahar Port Agreement",
    country: "Iran",
    value: "0.85B",
    status: "In Progress",
    type: "Trade",
    impact: "High Impact",
    description: "India contracted to develop and operate the Shahid Beheshti terminal at Chabahar Port in Iran for 10 years.",
    strategicIntent: "Create a trade corridor to Afghanistan and Central Asia bypassing Pakistan.",
    whyIndiaNeedsThis: "Chabahar gives India direct access to Afghanistan and Central Asian markets without Pakistani territory.",
    keyItems: ["Port terminal development", "Rail link to Zahedan", "INSTC route integration"],
    date: "2016"
  },
  {
    title: "India–ASEAN FTA (Free Trade in Goods Agreement)",
    country: "ASEAN",
    value: "100B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "Free trade agreement between India and the 10 ASEAN member nations on trade in goods.",
    strategicIntent: "Integrate India into Southeast Asian supply chains and boost Act East Policy.",
    whyIndiaNeedsThis: "ASEAN is India's 4th largest trading partner; FTA deepens economic ties.",
    keyItems: ["Tariff liberalisation on 80% goods", "Rules of origin", "ASEAN market access"],
    date: "January 2010"
  },
  {
    title: "India–UK Free Trade Agreement Negotiations",
    country: "United Kingdom",
    value: "120B",
    status: "In Progress",
    type: "Trade",
    impact: "High Impact",
    description: "Ongoing bilateral FTA negotiations between India and the United Kingdom post-Brexit.",
    strategicIntent: "Unlock a major English-speaking market for Indian services and goods.",
    whyIndiaNeedsThis: "UK is top destination for Indian IT services and students; FTA would formalise and expand this.",
    keyItems: ["Services liberalisation", "Visa mobility for professionals", "Goods tariff reduction"],
    date: "2022"
  },
  {
    title: "India Semiconductor Mission – Micron, TATA, Foxconn MoUs",
    country: "USA",
    value: "21B",
    status: "In Progress",
    type: "Technology",
    impact: "High Impact",
    description: "Series of MoUs with Micron Technology, Tata Electronics, and Foxconn to establish semiconductor fabs in India.",
    strategicIntent: "Build India into a global semiconductor manufacturing hub and reduce import dependence.",
    whyIndiaNeedsThis: "India imports 100% of its chips; domestic fab capacity is a national security imperative.",
    keyItems: ["Micron ATMP facility in Sanand", "Tata-PSMC fab in Dholera", "Foxconn fab in Taloja"],
    date: "2023"
  },
  {
    title: "India–France Strategic Partnership (Enhanced Defence)",
    country: "France",
    value: "20B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Elevated India-France strategic partnership encompassing defence, space, nuclear, and critical technologies.",
    strategicIntent: "Build a multi-dimensional partnership with Europe's leading defence power.",
    whyIndiaNeedsThis: "France offers technology transfer that US and Russia often restrict.",
    keyItems: ["Rafale jets", "Scorpene submarines", "Space cooperation", "Nuclear cooperation"],
    date: "2023"
  },
  {
    title: "India–Egypt Strategic Partnership",
    country: "Egypt",
    value: "7B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "Elevation of India-Egypt ties to Strategic Partnership with focus on defence and trade.",
    strategicIntent: "Access African and Arab markets and build influence in North Africa.",
    whyIndiaNeedsThis: "Egypt controls the Suez Canal, critical for India's trade with Europe.",
    keyItems: ["Defence cooperation", "Pharma exports", "IT sector investment"],
    date: "2023"
  },
  {
    title: "India–Africa Defence Cooperation Initiative",
    country: "African Union",
    value: "0",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India-Africa defence partnership covering training, capacity building, and equipment supply.",
    strategicIntent: "Counter China's growing military presence in Africa and build South-South partnerships.",
    whyIndiaNeedsThis: "Africa hosts vital Indian Ocean littoral states; influence there secures maritime routes.",
    keyItems: ["Military training slots", "Lines of credit for defence", "Joint exercises"],
    date: "2020"
  },
  {
    title: "India–Greece Defence and Economic MoU",
    country: "Greece",
    value: "2B",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India and Greece signed defence and economic MoUs during PM Modi's visit to Athens.",
    strategicIntent: "Expand India's footprint in Mediterranean Europe and build EU strategic ties.",
    whyIndiaNeedsThis: "Greece is a NATO member and key maritime nation; partnership opens European door.",
    keyItems: ["Defence MoU", "Shipping cooperation", "Trade facilitation"],
    date: "August 2023"
  },
  // ─────────────────────────────────────────────
  // NEW DEALS — filling gaps across all eras
  // ─────────────────────────────────────────────
  {
    title: "India–Philippines BrahMos Missile Export Deal",
    country: "Philippines",
    value: "0.375B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "The Philippines became the first export customer for BrahMos supersonic cruise missiles, marking India's entry into major defence exports.",
    strategicIntent: "Establish India as a credible defence exporter and strengthen Indo-Pacific partnerships.",
    whyIndiaNeedsThis: "Defence exports support domestic production scale and diplomatic influence.",
    keyItems: ["3 BrahMos shore-based batteries", "Anti-ship configuration", "Training and support package"],
    date: "January 2022"
  },
  {
    title: "India–Indonesia Defence Cooperation Agreement",
    country: "ASEAN",
    value: "0.1B",
    status: "Ongoing",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "Defence MoU covering joint exercises, training, and potential BrahMos and Tejas exports to Indonesia.",
    strategicIntent: "Expand India's defence exports and strategic partnerships in Southeast Asia.",
    whyIndiaNeedsThis: "Indonesia is a key Indo-Pacific partner; defence ties deepen Act East Policy.",
    keyItems: ["Joint naval exercises", "BrahMos export negotiations", "Tejas fighter evaluation"],
    date: "2023"
  },
  {
    title: "India–Vietnam Defence Partnership",
    country: "Vietnam",
    value: "0.5B",
    status: "Ongoing",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India extended a defence credit line to Vietnam for acquisition of military equipment including patrol vessels and radar systems.",
    strategicIntent: "Counter Chinese aggression in the South China Sea by strengthening Vietnam.",
    whyIndiaNeedsThis: "A stronger Vietnam diverts Chinese naval attention and supports India's Indo-Pacific strategy.",
    keyItems: ["Defence credit line", "Patrol vessels", "Radar systems"],
    date: "2016"
  },
  {
    title: "India–USA Semiconductor Fab Partnership (Applied Materials)",
    country: "USA",
    value: "0.4B",
    status: "In Progress",
    type: "Technology",
    impact: "Medium Impact",
    description: "Applied Materials signed an MoU with the Indian government for establishing semiconductor equipment manufacturing and training in India.",
    strategicIntent: "Develop an indigenous semiconductor equipment ecosystem as part of India Semiconductor Mission.",
    whyIndiaNeedsThis: "India needs fab equipment manufacturing to reduce import dependence in the chip sector.",
    keyItems: ["Equipment manufacturing", "Chip design training centre", "R&D collaboration"],
    date: "2023"
  },
  {
    title: "India–Japan Bullet Train Project (Mumbai-Ahmedabad HSR)",
    country: "Japan",
    value: "17B",
    status: "In Progress",
    type: "Technology",
    impact: "High Impact",
    description: "Japan is funding and providing technology for India's first high-speed rail corridor between Mumbai and Ahmedabad using Shinkansen E5 technology.",
    strategicIntent: "Develop India's high-speed rail ecosystem with technology transfer from Japan.",
    whyIndiaNeedsThis: "India needs modern rail infrastructure to reduce pressure on aviation and road networks.",
    keyItems: ["508 km HSR corridor", "E5 Shinkansen trains", "0.1% interest JICA loan", "Technology transfer"],
    date: "September 2017"
  },
  {
    title: "India–South Korea K9 Vajra Howitzer Deal",
    country: "South Korea",
    value: "0.65B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India inducted 100 K9 Vajra-T self-propelled howitzers from South Korea's Hanwha with production at L&T's Hazira plant.",
    strategicIntent: "Rapidly modernise Indian Army artillery with battle-proven self-propelled guns.",
    whyIndiaNeedsThis: "India had an artillery modernisation gap; K9 Vajra filled it with indigenous production.",
    keyItems: ["100 K9 Vajra-T howitzers", "L&T production line", "Desert and mountain variants"],
    date: "2017"
  },
  {
    title: "India–Sweden Saab Gripen Fighter Evaluation",
    country: "European Union",
    value: "0",
    status: "Proposed",
    type: "Defense Acquisition",
    impact: "Low Impact",
    description: "India evaluated the Saab Gripen NG as part of the MMRCA competition that was later cancelled.",
    strategicIntent: "Explore all options for IAF fighter modernisation.",
    whyIndiaNeedsThis: "India needed a competitive tender for MMRCA to get the best deal.",
    keyItems: ["Gripen NG evaluation", "Technology transfer offer", "Offset conditions"],
    date: "2011"
  },
  {
    title: "India–USA Westinghouse Nuclear Reactor Deal",
    country: "USA",
    value: "10B",
    status: "In Progress",
    type: "Energy",
    impact: "High Impact",
    description: "India and Westinghouse Electric agreed to build six AP1000 nuclear reactors at Kovvada, Andhra Pradesh.",
    strategicIntent: "Expand civilian nuclear power capacity and implement the 2008 India-US nuclear deal.",
    whyIndiaNeedsThis: "India needs massive nuclear capacity to meet electricity demand without increasing carbon emissions.",
    keyItems: ["6 AP1000 reactors", "Kovvada site, Andhra Pradesh", "7,000 MW capacity"],
    date: "2019"
  },
  {
    title: "India–France Nuclear Reactors at Jaitapur",
    country: "France",
    value: "15B",
    status: "In Progress",
    type: "Energy",
    impact: "High Impact",
    description: "India contracted EDF of France to build six EPR nuclear reactors at Jaitapur, Maharashtra, which would be the world's largest nuclear power plant.",
    strategicIntent: "Develop large-scale nuclear power capacity with French technology and financing.",
    whyIndiaNeedsThis: "Jaitapur's 9,900 MW capacity would power much of Maharashtra and reduce coal dependence.",
    keyItems: ["6 EPR reactors at Jaitapur", "9,900 MW capacity", "French financing support"],
    date: "2018"
  },
  {
    title: "India–Russia Kudankulam Nuclear Power Plant",
    country: "Russia",
    value: "6B",
    status: "In Progress",
    type: "Energy",
    impact: "High Impact",
    description: "Russia's Rosatom is building six VVER-1000 nuclear reactors at Kudankulam, Tamil Nadu. Units 1 and 2 are operational.",
    strategicIntent: "Expand India's nuclear power base with Russian VVER technology at Kudankulam.",
    whyIndiaNeedsThis: "India needs 25% of electricity from nuclear by 2047; Kudankulam is its biggest nuclear site.",
    keyItems: ["6 VVER-1000 reactors", "Units 1-2 operational", "Units 3-6 under construction"],
    date: "2001"
  },
  {
    title: "India–Norway Maritime and Ocean Economy MoU",
    country: "Norway",
    value: "0.2B",
    status: "Ongoing",
    type: "Trade",
    impact: "Low Impact",
    description: "India and Norway signed an MoU for cooperation in maritime sector including shipbuilding, fisheries, and ocean research.",
    strategicIntent: "Develop India's blue economy and maritime sector with Norwegian expertise.",
    whyIndiaNeedsThis: "India has a 7,500 km coastline and needs modern maritime infrastructure and fisheries management.",
    keyItems: ["Shipbuilding cooperation", "Fisheries management", "Offshore energy technology"],
    date: "2022"
  },
  {
    title: "India–Germany Green Hydrogen Partnership",
    country: "Germany",
    value: "1B",
    status: "In Progress",
    type: "Energy",
    impact: "Medium Impact",
    description: "India and Germany signed a strategic partnership for development of green hydrogen ecosystem including production, storage, and export.",
    strategicIntent: "Position India as a global green hydrogen hub and replace grey hydrogen in industry.",
    whyIndiaNeedsThis: "India's National Green Hydrogen Mission targets 5 MMTPA production; German technology accelerates this.",
    keyItems: ["Green hydrogen R&D", "Electrolyser manufacturing", "Export infrastructure"],
    date: "2023"
  },
  {
    title: "India–Switzerland Trade and Investment Agreement",
    country: "Switzerland",
    value: "0.3B",
    status: "Completed",
    type: "Trade",
    impact: "Low Impact",
    description: "Bilateral investment treaty and trade facilitation agreement between India and Switzerland.",
    strategicIntent: "Attract Swiss pharmaceutical, watch, and financial services investment to India.",
    whyIndiaNeedsThis: "Switzerland is a source of precision manufacturing and pharma investment for India.",
    keyItems: ["Investment protection", "Trade facilitation", "Pharma sector cooperation"],
    date: "2000"
  },
  {
    title: "India–Singapore CECA (Comprehensive Economic Cooperation Agreement)",
    country: "Singapore",
    value: "30B",
    status: "Completed",
    type: "Trade",
    impact: "High Impact",
    description: "India's first comprehensive FTA covering trade, investment, and services with Singapore.",
    strategicIntent: "Use Singapore as a gateway for India's trade and investment into Southeast Asia.",
    whyIndiaNeedsThis: "Singapore is India's largest FDI source; CECA formalized this relationship.",
    keyItems: ["Zero duty trade", "Investment facilitation", "Services liberalisation"],
    date: "August 2005"
  },
  {
    title: "India–Italy Augusta Westland VVIP Helicopter Deal",
    country: "Italy",
    value: "0.75B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Low Impact",
    description: "India contracted AgustaWestland for 12 AW101 VVIP helicopters for the Indian Air Force. The deal was later cancelled following bribery allegations.",
    strategicIntent: "Replace ageing Mi-8 helicopters for transporting the President, PM, and senior officials.",
    whyIndiaNeedsThis: "India needed modern VVIP transport helicopters with advanced safety and communications.",
    keyItems: ["12 AW101 helicopters", "VVIP configuration", "Contract cancelled 2014 due to corruption"],
    date: "2010"
  },
  {
    title: "India–Russia AK-203 Assault Rifle Manufacturing Deal",
    country: "Russia",
    value: "0.6B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India and Russia are jointly manufacturing AK-203 assault rifles at Korwa Ordnance Factory in Amethi for the Indian Army.",
    strategicIntent: "Replace the ageing INSAS rifle with a more capable assault rifle and build domestic manufacturing.",
    whyIndiaNeedsThis: "Indian Army's INSAS rifle was criticised for unreliability in extreme conditions; AK-203 is battle-proven.",
    keyItems: ["6.1 lakh AK-203 rifles", "Korwa Ordnance Factory production", "Over 70% indigenous content"],
    date: "2021"
  },
  {
    title: "India–USA GSOMIA Defence Intelligence Sharing",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "General Security of Military Information Agreement between India and the USA for sharing classified military intelligence.",
    strategicIntent: "Enable exchange of classified military information on shared threats, particularly China and Pakistan.",
    whyIndiaNeedsThis: "India needed formal intelligence sharing protocols with the US to leverage American surveillance capabilities.",
    keyItems: ["Classified info sharing", "Military intelligence exchange", "Threat assessment cooperation"],
    date: "2002"
  },
  {
    title: "India–Israel Spike-LR ATGM Production in India",
    country: "Israel",
    value: "0.13B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India and Israel signed an agreement for domestic production of Spike-LR anti-tank guided missiles at Bharat Dynamics Limited.",
    strategicIntent: "Reduce dependence on imported ATGMs and build domestic anti-tank missile manufacturing.",
    whyIndiaNeedsThis: "India needs to replace Milan ATGMs across its mechanised forces with modern fire-and-forget systems.",
    keyItems: ["Spike-LR missiles at BDL", "Technology transfer", "4th-gen ATGM capability"],
    date: "2021"
  },
  {
    title: "India–France Helicopter Engine JV (Safran-HAL)",
    country: "France",
    value: "0.2B",
    status: "In Progress",
    type: "Technology",
    impact: "Medium Impact",
    description: "HAL and Safran signed a joint venture for manufacturing helicopter engines in India, initially for the LUH and ALH programmes.",
    strategicIntent: "Build domestic helicopter engine manufacturing capability for strategic self-reliance.",
    whyIndiaNeedsThis: "India imports all helicopter engines; a domestic JV reduces strategic vulnerability.",
    keyItems: ["Ardiden 1U engine production", "HAL-Safran JV", "LUH and ALH programmes"],
    date: "2015"
  },
  {
    title: "India–UAE Defence Cooperation MoU",
    country: "UAE",
    value: "0.5B",
    status: "Ongoing",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India and UAE signed a defence MoU covering joint exercises, equipment sales, and maritime cooperation.",
    strategicIntent: "Deepen strategic ties with a key Gulf partner and potential market for Indian defence exports.",
    whyIndiaNeedsThis: "UAE offers strategic basing access in the Gulf and is an emerging buyer of Indian defence equipment.",
    keyItems: ["Joint military exercises", "Defence equipment sales", "Maritime security cooperation"],
    date: "2017"
  },
  {
    title: "India–USA F-16 (F-21) Fighter Production in India",
    country: "USA",
    value: "0",
    status: "Proposed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "Lockheed Martin offered to shift entire F-16 production line to India as part of MMRCA-2 bid.",
    strategicIntent: "India evaluated the offer as part of its single-engine fighter requirement.",
    whyIndiaNeedsThis: "India considered moving F-16 production to India to boost domestic defence manufacturing.",
    keyItems: ["F-21 for India variant", "Full production line transfer", "MMRCA-2 competition"],
    date: "2018"
  },
  {
    title: "India–Brazil Defence and Space MoU",
    country: "Brazil",
    value: "0.1B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Low Impact",
    description: "India and Brazil signed cooperation agreements in defence technology, space, and agriculture as part of South-South cooperation.",
    strategicIntent: "Build partnerships with emerging market democracies and diversify diplomatic relationships.",
    whyIndiaNeedsThis: "Brazil and India as large emerging democracies have complementary interests in multilateral forums.",
    keyItems: ["Space cooperation", "Defence technology exchange", "Agricultural research"],
    date: "2020"
  },
  {
    title: "India–Vietnam BrahMos Export Negotiations",
    country: "Vietnam",
    value: "0.25B",
    status: "Proposed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India is in advanced negotiations to export BrahMos cruise missiles to Vietnam for its navy.",
    strategicIntent: "Strengthen Vietnam's coastal defence against Chinese naval aggression.",
    whyIndiaNeedsThis: "BrahMos exports to Vietnam strengthen India's Indo-Pacific partnerships and generate revenue.",
    keyItems: ["Shore-based BrahMos batteries", "Anti-ship configuration", "Training package"],
    date: "2024"
  },
  {
    title: "India–Indonesia IKS (IDEX) Defence Expo Cooperation",
    country: "ASEAN",
    value: "0.05B",
    status: "Ongoing",
    type: "Defense Acquisition",
    impact: "Low Impact",
    description: "India and Indonesia signed MoUs for joint defence production and exchange of military personnel.",
    strategicIntent: "Build India's presence in Southeast Asian defence markets.",
    whyIndiaNeedsThis: "Indonesia is the largest economy in ASEAN; defence ties are strategically essential.",
    keyItems: ["Joint production MoU", "Personnel exchange", "Naval cooperation"],
    date: "2022"
  },
  {
    title: "India–USA AI and Cloud Partnership (Microsoft, Google, Amazon)",
    country: "USA",
    value: "4B",
    status: "In Progress",
    type: "Technology",
    impact: "High Impact",
    description: "Major US tech companies committed massive AI and cloud infrastructure investments in India including hyperscale data centres.",
    strategicIntent: "Position India as a global AI and digital services hub.",
    whyIndiaNeedsThis: "India needs AI infrastructure to support its digital economy, e-governance, and startup ecosystem.",
    keyItems: ["Microsoft $3B India investment", "Google data centres", "Amazon AWS expansion"],
    date: "2023"
  },
  {
    title: "India–USA Space Situational Awareness Agreement",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Technology",
    impact: "Medium Impact",
    description: "India and USA signed an agreement to share space situational awareness data to protect satellites from debris and collisions.",
    strategicIntent: "Protect India's growing satellite constellation from space debris threats.",
    whyIndiaNeedsThis: "India's space assets are critical for communications, navigation, and reconnaissance.",
    keyItems: ["Space debris tracking data", "Satellite conjunction warnings", "US Space Command coordination"],
    date: "2014"
  },
  {
    title: "India–France Space Cooperation Agreement (ISRO-CNES)",
    country: "France",
    value: "0.3B",
    status: "Ongoing",
    type: "Technology",
    impact: "Medium Impact",
    description: "ISRO and France's CNES have deep cooperation on satellite development, earth observation, and maritime surveillance.",
    strategicIntent: "Leverage French space expertise for India's civilian and dual-use space applications.",
    whyIndiaNeedsThis: "France has advanced earth observation and satellite technology India benefits from.",
    keyItems: ["Joint earth observation satellites", "Maritime surveillance", "Launch vehicle cooperation"],
    date: "2008"
  },
  {
    title: "India–Israel Skystriker Kamikaze Drone Deal",
    country: "Israel",
    value: "0.2B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India purchased Elbit Systems Skystriker loitering munitions for the Indian Army.",
    strategicIntent: "Provide frontline units with a precision strike loitering munition.",
    whyIndiaNeedsThis: "Post-Galwan, India needed combat drones rapidly; Skystriker gave immediate standoff precision capability.",
    keyItems: ["Skystriker loitering munitions", "Precision GPS guidance", "Anti-armour warhead"],
    date: "2020"
  },
  {
    title: "India–Russia Advanced Technology Vessel (ATV) Nuclear Sub Assistance",
    country: "Russia",
    value: "0",
    status: "Completed",
    type: "Technology",
    impact: "High Impact",
    description: "Russia provided critical design assistance and propulsion technology for India's Advanced Technology Vessel programme that produced INS Arihant.",
    strategicIntent: "Develop India's sea-based nuclear deterrent for the nuclear triad.",
    whyIndiaNeedsThis: "A credible sea-based deterrent is essential for India's second-strike nuclear capability.",
    keyItems: ["Naval nuclear reactor design", "Propulsion system assistance", "Training of Indian engineers"],
    date: "1985"
  },
  {
    title: "India–South Korea POSCO Steel Investment",
    country: "South Korea",
    value: "12B",
    status: "Proposed",
    type: "Trade",
    impact: "Medium Impact",
    description: "POSCO of South Korea proposed a $12 billion integrated steel plant investment in Odisha, India's largest proposed FDI at the time.",
    strategicIntent: "Attract large-scale FDI for India's steel manufacturing expansion.",
    whyIndiaNeedsThis: "India needs to multiply steel capacity for infrastructure needs.",
    keyItems: ["12 MTPA steel plant", "Odisha site", "Iron ore supply"],
    date: "2005"
  },
  {
    title: "India–USA DTTI (Defence Technology and Trade Initiative)",
    country: "USA",
    value: "0",
    status: "Ongoing",
    type: "Technology",
    impact: "High Impact",
    description: "Joint working groups for co-development and co-production of defence equipment including aircraft carrier technology and jet engine development.",
    strategicIntent: "Move India-US defence relationship beyond buyer-seller to genuine co-development.",
    whyIndiaNeedsThis: "India needs access to cutting-edge US defence technology for self-reliance.",
    keyItems: ["Aircraft carrier technology sharing", "Jet engine co-development", "Infantry equipment projects"],
    date: "2012"
  },
  {
    title: "India–China Doklam Disengagement Understanding",
    country: "China",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "Diplomatic agreement to disengage Indian and Chinese troops from the Doklam plateau standoff.",
    strategicIntent: "Resolve a dangerous military standoff without armed conflict.",
    whyIndiaNeedsThis: "Doklam controls the Siliguri Corridor; India could not allow Chinese construction there.",
    keyItems: ["Troop withdrawal", "Status quo maintained", "No formal written agreement"],
    date: "August 2017"
  },
  {
    title: "India–China Galwan LAC Disengagement Agreement",
    country: "China",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "High Impact",
    description: "Phased military disengagement agreement following the fatal Galwan clash of June 2020 between Indian and Chinese troops.",
    strategicIntent: "Reduce military tension along the LAC and restore status quo ante.",
    whyIndiaNeedsThis: "Post-Galwan, both armies were in dangerous proximity; disengagement was essential.",
    keyItems: ["Gogra-Hot Springs disengagement", "Pangong Tso buffer zone", "Depsang negotiations"],
    date: "2021"
  },
  {
    title: "India–Japan Defence Equipment and Technology Transfer Agreement",
    country: "Japan",
    value: "0.5B",
    status: "Ongoing",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India and Japan signed agreements for transfer of defence equipment and technology including potential US-2 amphibious aircraft.",
    strategicIntent: "Deepen defence industrial cooperation with Japan as a hedge against China.",
    whyIndiaNeedsThis: "Japan's advanced defence technologies complement India's procurement needs.",
    keyItems: ["US-2 amphibious aircraft evaluation", "Sonar technology", "Joint R&D projects"],
    date: "2015"
  },
  {
    title: "India–Australia Mutual Logistics Support Agreement",
    country: "Australia",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India and Australia signed a mutual logistics support agreement for navy and air force operations.",
    strategicIntent: "Expand operational reach of Indian forces in the Indo-Pacific using Australian bases.",
    whyIndiaNeedsThis: "Australia's base access extends India's logistical footprint in the eastern Indian Ocean.",
    keyItems: ["Mutual base access", "Fuel and maintenance support", "Navy port calls"],
    date: "2020"
  },
  {
    title: "India–Canada Uranium Supply Agreement",
    country: "Canada",
    value: "0.3B",
    status: "Completed",
    type: "Energy",
    impact: "High Impact",
    description: "India and Canada signed agreements for Cameco of Canada to supply uranium to India's civilian nuclear reactors under IAEA safeguards.",
    strategicIntent: "Secure reliable uranium fuel supply for India's growing civilian nuclear programme.",
    whyIndiaNeedsThis: "India's civilian nuclear reactors need reliable uranium supply after the 2008 nuclear deal.",
    keyItems: ["Uranium supply contracts", "IAEA safeguards compliance", "Cameco-NPCIL agreement"],
    date: "2015"
  },
  {
    title: "India–Kazakhstan Uranium Purchase Agreement",
    country: "Multilateral",
    value: "0.15B",
    status: "Ongoing",
    type: "Energy",
    impact: "Medium Impact",
    description: "India's Uranium Corporation signed agreements with Kazakhstan's Kazatomprom for uranium supply.",
    strategicIntent: "Diversify uranium supply sources to ensure fuel security for nuclear plants.",
    whyIndiaNeedsThis: "India imports 75% of its uranium; diversified sources reduce strategic vulnerability.",
    keyItems: ["Uranium supply agreements", "Joint mining exploration", "IAEA safeguards application"],
    date: "2009"
  },
  {
    title: "India–Mongolia Strategic Partnership",
    country: "Multilateral",
    value: "0.2B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Low Impact",
    description: "India and Mongolia established strategic partnership with uranium supply, defence training, and developmental cooperation.",
    strategicIntent: "Build a strategic partner between China and Russia that can supply uranium.",
    whyIndiaNeedsThis: "Mongolia is a source of uranium and a buffer between China and Russia.",
    keyItems: ["Uranium supply MoU", "Military training", "Development assistance"],
    date: "2015"
  },
  {
    title: "India–Myanmar Border Trade Agreement",
    country: "ASEAN",
    value: "0.5B",
    status: "Ongoing",
    type: "Trade",
    impact: "Low Impact",
    description: "Bilateral border trade agreement between India and Myanmar facilitating cross-border commerce in Northeast India.",
    strategicIntent: "Develop Northeast India's economy and build connectivity with Southeast Asia.",
    whyIndiaNeedsThis: "Myanmar is India's gateway to ASEAN; border trade reduces isolation of Northeast India.",
    keyItems: ["Moreh-Tamu border trade", "Kaladan Multi-Modal project", "India-Myanmar-Thailand highway"],
    date: "2006"
  },
  {
    title: "India–Russia 5th Generation Fighter Aircraft (FGFA) Programme",
    country: "Russia",
    value: "4B",
    status: "Proposed",
    type: "Technology",
    impact: "High Impact",
    description: "India and Russia jointly developed a 5th-generation stealth fighter based on the Su-57 platform. India withdrew in 2018 citing performance concerns.",
    strategicIntent: "Develop a 5th-gen stealth fighter for IAF to match Chinese J-20.",
    whyIndiaNeedsThis: "IAF needs a 5th-gen fighter to maintain air superiority as China and Pakistan modernise.",
    keyItems: ["Su-57 based FGFA", "India-specific modifications", "India withdrew 2018"],
    date: "2007"
  },
  {
    title: "India–USA Harpoon Anti-Ship Missile Deal",
    country: "USA",
    value: "0.2B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India purchased AGM-84L Harpoon Block II air-launched anti-ship missiles for its P-8I Poseidon maritime patrol aircraft.",
    strategicIntent: "Provide Indian Navy's P-8I fleet with standoff anti-ship strike capability.",
    whyIndiaNeedsThis: "P-8I aircraft needed a compatible long-range anti-ship missile to be fully combat-effective.",
    keyItems: ["AGM-84L Harpoon Block II", "P-8I integration", "Anti-ship maritime strike"],
    date: "2020"
  },
  {
    title: "India–USA Javelin Anti-Tank Missile Deal",
    country: "USA",
    value: "0.1B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "Medium Impact",
    description: "India purchased Javelin fire-and-forget anti-tank guided missiles from the USA for mountain warfare units.",
    strategicIntent: "Provide infantry with man-portable anti-armour capability in high-altitude terrain.",
    whyIndiaNeedsThis: "Post-Galwan standoff, India needed to rapidly upgrade anti-armour capability in Ladakh.",
    keyItems: ["Javelin ATGM", "Fire-and-forget guidance", "Mountain warfare deployment"],
    date: "2021"
  },
  {
    title: "India–Russia Su-30MKI Fighter Aircraft Deal",
    country: "Russia",
    value: "10B",
    status: "Completed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India's largest ever defence acquisition — 272 Su-30MKI twin-engine fighters with license production at HAL Nasik.",
    strategicIntent: "Provide IAF with a world-class air superiority fighter as backbone of its combat fleet.",
    whyIndiaNeedsThis: "Su-30MKI gave IAF a powerful 4+ gen fighter superior to Pakistani F-16s and equivalent to Chinese aircraft.",
    keyItems: ["272 Su-30MKI aircraft", "HAL production line", "AL-31FP engines", "India-specific avionics"],
    date: "November 1996"
  },
  {
    title: "India–France Partnership and France-India 21st Century Roadmap",
    country: "France",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India and France signed a strategic roadmap for 21st-century cooperation covering space, defence, climate, and digital domains.",
    strategicIntent: "Institutionalise the broad-based India-France partnership for next generation cooperation.",
    whyIndiaNeedsThis: "France is a critical partner for technology, defence and nuclear energy where others have restrictions.",
    keyItems: ["Horizon 2047 roadmap", "Defence co-production", "Space cooperation"],
    date: "July 2023"
  },
  {
    title: "India–USA IMEEC (India-Middle East-Europe Corridor)",
    country: "USA",
    value: "20B",
    status: "Proposed",
    type: "Trade",
    impact: "High Impact",
    description: "India-Middle East-Europe Economic Corridor announced at G20 to connect India to Europe through UAE, Saudi Arabia, Jordan, and Israel.",
    strategicIntent: "Counter China's Belt and Road Initiative and create an alternative trade corridor.",
    whyIndiaNeedsThis: "IMEEC reduces shipping time to Europe by 40% and diversifies India's trade routes.",
    keyItems: ["Rail-ship corridor", "UAE and Saudi transit", "Connectivity to Greece and Italy"],
    date: "September 2023"
  },
  {
    title: "India–USA Strategic Trade Authorisation-1 (STA-1)",
    country: "USA",
    value: "0",
    status: "Completed",
    type: "Technology",
    impact: "High Impact",
    description: "USA granted India STA-1 status — the highest level of export control trust — enabling easier transfer of high-technology goods.",
    strategicIntent: "Remove bureaucratic barriers to US-India tech trade and defence procurement.",
    whyIndiaNeedsThis: "STA-1 allows India to procure sensitive US dual-use technology without lengthy case-by-case approvals.",
    keyItems: ["High-tech export facilitation", "Dual-use technology access", "Reduced licensing burden"],
    date: "2018"
  },
  {
    title: "India–Germany Strategic Partnership",
    country: "Germany",
    value: "0",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India and Germany elevated ties to a Strategic Partnership with annual bilateral consultations at the intergovernmental level.",
    strategicIntent: "Deepen political, economic, and technological ties with Europe's largest economy.",
    whyIndiaNeedsThis: "Germany is India's largest trading partner in Europe and a source of industrial technology.",
    keyItems: ["Intergovernmental consultations", "Climate cooperation", "Industrial technology transfer"],
    date: "2011"
  },
  {
    title: "India–Italy Defence Cooperation MoU",
    country: "Italy",
    value: "0.3B",
    status: "Ongoing",
    type: "Defense Acquisition",
    impact: "Low Impact",
    description: "India and Italy signed defence cooperation agreements covering naval shipbuilding and joint military training.",
    strategicIntent: "Access European naval technology and build alternative defence supply chains.",
    whyIndiaNeedsThis: "Italy's Finmeccanica offered niche naval and aeronautical systems for Indian requirements.",
    keyItems: ["Naval cooperation", "Training agreements", "Defence equipment cooperation"],
    date: "2018"
  },
  {
    title: "India–USA Overseas Private Investment Corporation (OPIC) Agreement",
    country: "USA",
    value: "1B",
    status: "Completed",
    type: "Trade",
    impact: "Low Impact",
    description: "OPIC extended $1B in financing facilities to support US private investment in India across infrastructure, healthcare, and energy sectors.",
    strategicIntent: "Attract American private capital to India's development projects.",
    whyIndiaNeedsThis: "India needs foreign private capital to supplement government spending on infrastructure.",
    keyItems: ["Infrastructure financing", "Healthcare investments", "Energy sector support"],
    date: "2016"
  },
  {
    title: "India–China Bilateral Investment Treaty Negotiations",
    country: "China",
    value: "0",
    status: "Proposed",
    type: "Trade",
    impact: "Low Impact",
    description: "Ongoing and stalled negotiations for a bilateral investment treaty between India and China.",
    strategicIntent: "Create a formal framework for managing Chinese FDI into India.",
    whyIndiaNeedsThis: "India wants Chinese investment in manufacturing but needs safeguards for national security.",
    keyItems: ["Investment protection provisions", "Dispute settlement mechanism", "Stalled post-Galwan"],
    date: "2015"
  },
  {
    title: "India–Vietnam Strategic Partnership Upgrade",
    country: "Vietnam",
    value: "0.5B",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India elevated ties with Vietnam to a Comprehensive Strategic Partnership covering defence, trade, and culture.",
    strategicIntent: "Deepen strategic ties with a key South China Sea nation to counter Chinese assertiveness.",
    whyIndiaNeedsThis: "Vietnam's position in the South China Sea makes it a critical partner for India's Indo-Pacific strategy.",
    keyItems: ["Defence credit line", "Naval cooperation", "Cultural and educational exchange"],
    date: "2020"
  },
  {
    title: "India–Indonesia Comprehensive Strategic Partnership",
    country: "ASEAN",
    value: "0.8B",
    status: "Ongoing",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India and Indonesia upgraded ties to Comprehensive Strategic Partnership covering maritime, defence, trade, and digital sectors.",
    strategicIntent: "Deepen ties with the world's largest archipelago nation and ASEAN's biggest economy.",
    whyIndiaNeedsThis: "Indonesia controls the Malacca and Lombok straits — critical chokepoints for Indian trade.",
    keyItems: ["Maritime security cooperation", "Defence equipment exports", "Digital and trade partnership"],
    date: "2023"
  },
  {
    title: "India–USA Semiconductor Talent and Education Partnership",
    country: "USA",
    value: "0.1B",
    status: "In Progress",
    type: "Technology",
    impact: "Medium Impact",
    description: "Partnership between US and Indian universities for semiconductor chip design education and workforce development.",
    strategicIntent: "Develop the talent pipeline needed for India's semiconductor ambitions.",
    whyIndiaNeedsThis: "India needs 85,000 chip designers by 2026; this partnership builds that workforce.",
    keyItems: ["Chip design curriculum", "University partnerships", "CHIPS for America collaboration"],
    date: "2023"
  },
  {
    title: "India–Germany P-75I Submarine Deal",
    country: "Germany",
    value: "8.3B",
    status: "In Progress",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India and Germany are finalising an agreement for the joint construction of six Type-214 conventionally powered submarines under Project 75I, with ThyssenKrupp Marine Systems partnering Mazagon Dock.",
    strategicIntent: "Expand India's submarine fleet with AIP technology and build domestic submarine manufacturing.",
    whyIndiaNeedsThis: "India's submarine fleet has shrunk to 16 boats; Project 75I is critical to rebuild undersea deterrence.",
    keyItems: ["6 Type-214 submarines with AIP", "Mazagon Dock production", "60% indigenous content"],
    date: "January 2026"
  },
  {
    title: "India–Israel Precision Strike Weapons Package",
    country: "Israel",
    value: "8.7B",
    status: "Signed",
    type: "Defense Acquisition",
    impact: "High Impact",
    description: "India signed a landmark deal with Israel for 1,000 SPICE-1000 precision bomb kits, Rampage supersonic missiles, and Air Lora ballistic missiles.",
    strategicIntent: "Dramatically enhance IAF's deep-strike precision capability against hardened targets.",
    whyIndiaNeedsThis: "Post-Balakot, India needs a large inventory of precision munitions for potential two-front conflict.",
    keyItems: ["1,000 SPICE-1000 precision kits", "Rampage supersonic missiles", "Air Lora ballistic missiles"],
    date: "February 2026"
  },
  {
    title: "India–USA Bilateral Trade Agreement (Trump-Modi Deal)",
    country: "USA",
    value: "500B",
    status: "In Progress",
    type: "Trade",
    impact: "High Impact",
    description: "A landmark trade framework where Trump reduced tariffs on Indian goods from 50% to 18% and India committed to purchasing $500B in US products over five years including energy, defence, and technology.",
    strategicIntent: "Reset India-US trade relations and build a deeper economic partnership.",
    whyIndiaNeedsThis: "India needed to avoid trade war with the US; this deal secures market access and attracts US investment.",
    keyItems: ["Tariff cut from 50% to 18%", "$500B US goods purchase commitment", "Energy and defence procurement"],
    date: "February 2026"
  },
  {
    title: "India–France Bilateral Partnership (Modi Paris Visit)",
    country: "France",
    value: "0",
    status: "Completed",
    type: "Diplomatic",
    impact: "Medium Impact",
    description: "India and France signed a 21-point outcome statement during PM Modi's Paris visit, deepening bilateral ties in defence, minerals, and student exchange.",
    strategicIntent: "Institutionalise the comprehensive India-France strategic partnership.",
    whyIndiaNeedsThis: "France is a key European partner for Rafale jets, Scorpene submarines, and nuclear reactors.",
    keyItems: ["21-point outcome statement", "Minerals partnership", "Student exchange programme"],
    date: "February 2026"
  },
  {
    title: "India–Croatia Bilateral Cooperation",
    country: "Croatia",
    value: "0",
    status: "Proposed",
    type: "Diplomatic",
    impact: "Low Impact",
    description: "PM Modi met Croatian PM Andrej Plenkovic to explore cooperation in technology, shipbuilding, and bilateral trade.",
    strategicIntent: "Expand India's European diplomatic footprint to smaller EU member states.",
    whyIndiaNeedsThis: "Croatia is a maritime nation with shipbuilding expertise and EU access relevant to India.",
    keyItems: ["Shipbuilding cooperation", "Technology exchange", "Trade facilitation"],
    date: "February 2026"
  },
  {
    title: "India–USA Pax Silica Alliance",
    country: "USA",
    value: "0",
    status: "Proposed",
    type: "Technology",
    impact: "High Impact",
    description: "India is set to join the US-led Pax Silica alliance for building robust supply chains for critical minerals and AI infrastructure.",
    strategicIntent: "Secure India's position in the AI and semiconductor supply chain.",
    whyIndiaNeedsThis: "India needs to align with allied nations to counter China's dominance in critical minerals and AI hardware.",
    keyItems: ["Critical minerals supply chains", "AI infrastructure cooperation", "Semiconductor resilience"],
    date: "2026"
  },
  {
    title: "India–Brazil Trade Deal Explorations",
    country: "Brazil",
    value: "20B",
    status: "Proposed",
    type: "Trade",
    impact: "Medium Impact",
    description: "India and Brazil are exploring a bilateral trade deal to increase trade from $12B to $20B, focusing on energy, food, and pharma.",
    strategicIntent: "Strengthen South-South trade ties with Latin America's largest economy.",
    whyIndiaNeedsThis: "Brazil offers agricultural commodities, oil, and rare earths that India needs to diversify imports.",
    keyItems: ["Crude oil imports", "Agricultural commodities", "Pharma exports from India"],
    date: "2026"
  },
];