// deals-infra/main.go
//
// DISASTER RECOVERY TOOL
// ──────────────────────
// This Go program describes your ENTIRE India Deals Tracker infrastructure
// as a Terraform config. If your current cloud goes down:
//
//   1. Change TARGET_CLOUD in config (vercel → railway)
//   2. go run main.go deploy
//   3. Your entire app is back online in ~10 minutes
//
// Commands:
//   go run main.go deploy    → generate .tf + terraform apply (full deploy)
//   go run main.go plan      → dry run, show what would change
//   go run main.go generate  → only write the .tf file, don't apply
//   go run main.go status    → show what's currently deployed
//   go run main.go destroy   → tear everything down (disaster simulation)
//   go run main.go help      → show all commands
//
// First time setup:
//   brew install terraform
//   export VERCEL_API_TOKEN="your_token"       ← vercel.com → Settings → Tokens
//   export VERCEL_PROJECT_ID="prj_xxxxxxx"     ← vercel.com → project → Settings
//   export VERCEL_ORG_ID="team_xxxxxxx"        ← vercel.com → Settings → Team ID
//   export MONGODB_URI="mongodb+srv://..."      ← your .env.local
//   export NEWS_API_KEY="fa59235d..."
//   export GROQ_API_KEY="gsk_4Iiw..."
//   export CRON_SECRET="mySuperSecret123"
//   export GITHUB_REPO="vipuljain675-projects/Indian-Deal-Tracker-"

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

// ── Colours ──

func green(s string) string  { return "\033[32m" + s + "\033[0m" }
func red(s string) string    { return "\033[31m" + s + "\033[0m" }
func yellow(s string) string { return "\033[33m" + s + "\033[0m" }
func bold(s string) string   { return "\033[1m" + s + "\033[0m" }
func cyan(s string) string   { return "\033[36m" + s + "\033[0m" }
func grey(s string) string   { return "\033[90m" + s + "\033[0m" }

// ── AppConfig: everything needed to deploy your app ──
// This is the single source of truth for your infrastructure

type AppConfig struct {
	// App identity
	AppName    string
	Framework  string
	GitRepo    string // "owner/repo-name" on GitHub

	// Cloud target — change this to switch clouds
	// "vercel" = deploy to Vercel
	// (future: "railway", "render", "netlify")
	TargetCloud string

	// Vercel specific
	VercelOrgID     string
	VercelProjectID string

	// Environment variables — your app secrets
	// Go reads these from actual env vars (which you loaded from .env.local)
	EnvVars map[string]string
}

// loadConfig reads all required values from environment variables
// This is the Go equivalent of reading .env.local
func loadConfig() (*AppConfig, []string) {
	var missing []string

	get := func(key string) string {
		val := os.Getenv(key)
		if val == "" {
			missing = append(missing, key)
		}
		return val
	}

	// Optional — has defaults
	targetCloud := os.Getenv("TARGET_CLOUD")
	if targetCloud == "" {
		targetCloud = "vercel" // default to Vercel
	}

	cfg := &AppConfig{
		AppName:     "india-deals-tracker",
		Framework:   "nextjs",
		GitRepo:     os.Getenv("GITHUB_REPO"),
		TargetCloud: targetCloud,

		VercelOrgID:     get("VERCEL_ORG_ID"),
		VercelProjectID: get("VERCEL_PROJECT_ID"),

		// All 4 env vars your Next.js app needs
		EnvVars: map[string]string{
			"MONGODB_URI":   get("MONGODB_URI"),
			"NEWS_API_KEY":  get("NEWS_API_KEY"),
			"GROQ_API_KEY":  get("GROQ_API_KEY"),
			"CRON_SECRET":   get("CRON_SECRET"),
		},
	}

	// VERCEL_API_TOKEN is used by terraform provider directly
	// so we just check it exists
	if os.Getenv("VERCEL_API_TOKEN") == "" {
		missing = append(missing, "VERCEL_API_TOKEN")
	}

	return cfg, missing
}

// ── Step 2: Generate Terraform config ──
// This is the core — Go writes the ENTIRE infrastructure as a .tf file

func generateTerraformConfig(cfg *AppConfig) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`# ================================================================
# INDIA DEALS TRACKER — FULL INFRASTRUCTURE
# Auto-generated by deals-infra Go tool
# Generated: %s
# Target cloud: %s
#
# This file describes your ENTIRE app infrastructure.
# To redeploy on a new cloud:
#   1. Change TARGET_CLOUD env var
#   2. go run main.go deploy
# ================================================================

`, time.Now().Format("2006-01-02 15:04:05"), cfg.TargetCloud))

	// ── Terraform providers block ──
	// This tells Terraform which cloud provider plugin to download
	sb.WriteString(`terraform {
  required_providers {
    vercel = {
      source  = "vercel/vercel"
      version = "~> 1.0"
    }
  }

  # State file — tracks what's deployed
  # For a team, move this to S3 or Terraform Cloud
  # For solo project, local file is fine
  backend "local" {
    path = "terraform.tfstate"
  }
}

# Vercel provider authenticates using VERCEL_API_TOKEN env var
provider "vercel" {}

`)

	// ── Core resource: The Vercel Project ──
	// This IS your app on Vercel — the equivalent of clicking
	// "New Project" in the Vercel dashboard
	sb.WriteString(fmt.Sprintf(`# ── VERCEL PROJECT ──
# This creates/manages your Next.js project on Vercel
resource "vercel_project" "india_deals_tracker" {
  name      = "%s"
  team_id   = "%s"
  framework = "%s"

  # Automatically deploy when you push to main branch
  git_repository = {
    type              = "github"
    repo              = "%s"
    production_branch = "main"
  }

  # Build settings — same as your current Vercel config
  build_command    = "npm run build"
  output_directory = ".next"
  install_command  = "npm install"

  # Serverless function region — ap-south-1 = Mumbai (closest to India!)
  serverless_function_region = "bom1"
}

`, cfg.AppName, cfg.VercelOrgID, cfg.Framework, cfg.GitRepo))

	// ── Environment Variables ──
	// Each env var is a separate Terraform resource
	// Terraform tracks each one individually — if you change
	// MONGODB_URI, it only updates that one, leaves others untouched
	sb.WriteString("# ── ENVIRONMENT VARIABLES ──\n")
	sb.WriteString("# These are your app secrets — synced to Vercel automatically\n\n")

	// Define which environments each var goes to
	envTargets := map[string]string{
		"MONGODB_URI":  `["production", "preview", "development"]`,
		"NEWS_API_KEY": `["production", "preview"]`,
		"GROQ_API_KEY": `["production", "preview", "development"]`,
		"CRON_SECRET":  `["production"]`, // cron only runs in production
	}

	// Sensitive vars — Terraform will mark these as sensitive
	// so they don't show in logs
	sensitiveVars := map[string]bool{
		"MONGODB_URI":  true,
		"GROQ_API_KEY": true,
		"NEWS_API_KEY": true,
		"CRON_SECRET":  true,
	}

	for key, value := range cfg.EnvVars {
		resourceName := strings.ToLower(key)
		targets := envTargets[key]
		if targets == "" {
			targets = `["production", "preview", "development"]`
		}
		sensitive := sensitiveVars[key]

		sb.WriteString(fmt.Sprintf(`resource "vercel_env_var" "%s" {
  project_id = vercel_project.india_deals_tracker.id
  team_id    = "%s"
  key        = "%s"
  value      = "%s"
  target     = %s
  sensitive  = %v
}

`, resourceName, cfg.VercelOrgID, key, escapeTF(value), targets, sensitive))
	}

	// ── Outputs ──
	// After terraform apply, these values are printed to terminal
	// So you immediately know your deployment URLs
	sb.WriteString(`# ── OUTPUTS ──
# These are printed after terraform apply completes
# So you know exactly where your app is deployed

output "project_url" {
  description = "Your app's production URL"
  value       = "https://${vercel_project.india_deals_tracker.name}.vercel.app"
}

output "project_id" {
  description = "Vercel project ID (save this!)"
  value       = vercel_project.india_deals_tracker.id
}

output "deployment_info" {
  description = "Summary of what was deployed"
  value = {
    app       = vercel_project.india_deals_tracker.name
    framework = vercel_project.india_deals_tracker.framework
    region    = vercel_project.india_deals_tracker.serverless_function_region
    branch    = "main"
  }
}
`)

	return sb.String()
}

func escapeTF(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, `$`, `\$`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	return s
}

// ── Terraform runner ──

func checkTerraform() bool {
	_, err := exec.LookPath("terraform")
	return err == nil
}

// runTF runs a terraform command, streaming output to terminal
func runTF(args []string) error {
	cmd := exec.Command("terraform", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run()
}

// runTFCapture runs terraform and captures output (for status checks)
func runTFCapture(args []string) (string, error) {
	cmd := exec.Command("terraform", args...)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	err := cmd.Run()
	return out.String(), err
}

// readEnvFile reads .env.local and sets env vars in the current process
// This means users can just have .env.local and don't need to export everything
func readEnvFile(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	count := 0
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), `"'`)

		// Only set if not already set (don't override explicit exports)
		if os.Getenv(key) == "" {
			os.Setenv(key, value)
			count++
		}
	}
	fmt.Printf("%s Loaded %d vars from %s\n", grey("→"), count, cyan(path))
	return scanner.Err()
}

// ── Commands ──

func cmdDeploy(cfg *AppConfig) {
	fmt.Println(bold("\n🚀 India Deals Tracker — Full Infrastructure Deploy"))
	fmt.Println(strings.Repeat("─", 55))
	fmt.Printf("  App        : %s\n", bold(cfg.AppName))
	fmt.Printf("  Framework  : %s\n", cfg.Framework)
	fmt.Printf("  Target     : %s\n", cyan(cfg.TargetCloud))
	fmt.Printf("  Repository : %s\n", cfg.GitRepo)
	fmt.Printf("  Env vars   : %d variables\n", len(cfg.EnvVars))
	fmt.Println(strings.Repeat("─", 55))

	// Generate .tf file
	fmt.Println("\n📝 Step 1/3 — Generating infrastructure.tf...")
	tfContent := generateTerraformConfig(cfg)
	if err := os.WriteFile("infrastructure.tf", []byte(tfContent), 0644); err != nil {
		fmt.Println(red("❌ Cannot write infrastructure.tf: " + err.Error()))
		return
	}
	fmt.Println(green("   ✓ infrastructure.tf written"))
	fmt.Printf("   %s\n", grey("Describes: 1 Vercel project + "+
		fmt.Sprintf("%d", len(cfg.EnvVars))+" env vars + GitHub connection + outputs"))

	// terraform init
	fmt.Println("\n📦 Step 2/3 — terraform init (downloading Vercel provider)...")
	fmt.Println(strings.Repeat("─", 55))
	if err := runTF([]string{"init", "-upgrade"}); err != nil {
		fmt.Println(red("\n❌ terraform init failed"))
		return
	}

	// terraform apply
	fmt.Println(strings.Repeat("─", 55))
	fmt.Println("\n⚡ Step 3/3 — terraform apply (deploying to " + cfg.TargetCloud + ")...")
	fmt.Println(grey("   Terraform will show you the plan first."))
	fmt.Println(grey("   Review it, then type 'yes' to confirm."))
	fmt.Println(strings.Repeat("─", 55))

	if err := runTF([]string{"apply"}); err != nil {
		fmt.Println(red("\n❌ terraform apply failed"))
		fmt.Println(grey("   Check the error above. Common issues:"))
		fmt.Println(grey("   - Invalid VERCEL_API_TOKEN"))
		fmt.Println(grey("   - Project already exists with different settings"))
		fmt.Println(grey("   - GitHub repo not connected to Vercel"))
		return
	}

	fmt.Printf("\n%s\n", green("✅ Deploy complete! Your app is live."))
	fmt.Println(grey("   Vercel will now auto-deploy on every git push to main."))
	fmt.Println()
}

func cmdPlan(cfg *AppConfig) {
	fmt.Println(bold("\n🔍 Infrastructure Plan — Dry Run (no changes will be made)"))
	fmt.Println(strings.Repeat("─", 55))

	tfContent := generateTerraformConfig(cfg)
	os.WriteFile("infrastructure.tf", []byte(tfContent), 0644)
	fmt.Println(green("✓ infrastructure.tf generated"))

	fmt.Println("\n📦 Running terraform init...")
	runTF([]string{"init", "-upgrade"})

	fmt.Println("\n🔍 Running terraform plan...")
	fmt.Println(strings.Repeat("─", 55))
	runTF([]string{"plan"})
}

func cmdGenerate(cfg *AppConfig) {
	fmt.Println(bold("\n📝 Generating infrastructure.tf only"))
	fmt.Println(strings.Repeat("─", 55))

	tfContent := generateTerraformConfig(cfg)
	if err := os.WriteFile("infrastructure.tf", []byte(tfContent), 0644); err != nil {
		fmt.Println(red("❌ " + err.Error()))
		return
	}

	fmt.Println(green("✅ Written to: infrastructure.tf"))
	fmt.Println(grey("\nFile contents:\n"))
	fmt.Println(grey(strings.Repeat("─", 55)))

	// Print with line numbers
	lines := strings.Split(tfContent, "\n")
	for i, line := range lines {
		fmt.Printf("%s %s\n", grey(fmt.Sprintf("%3d |", i+1)), line)
	}
}

func cmdStatus() {
	fmt.Println(bold("\n📊 Infrastructure Status"))
	fmt.Println(strings.Repeat("─", 55))

	// Check if state file exists
	if _, err := os.Stat("terraform.tfstate"); os.IsNotExist(err) {
		fmt.Println(yellow("⚠️  No state file found."))
		fmt.Println(grey("   Nothing has been deployed yet with this tool."))
		fmt.Println(grey("   Run: go run main.go deploy"))
		return
	}

	// Show state
	output, err := runTFCapture([]string{"show", "-no-color"})
	if err != nil || strings.TrimSpace(output) == "" || output == "The state file is empty. No resources are represented." {
		fmt.Println(yellow("⚠️  No resources currently deployed."))
		return
	}

	fmt.Println(output)

	// Also show outputs
	fmt.Println(bold("\n🔗 Deployment Outputs:"))
	fmt.Println(strings.Repeat("─", 55))
	runTF([]string{"output"})
}

func cmdDestroy() {
	fmt.Println(bold("\n💥 Infrastructure Destroy"))
	fmt.Println(strings.Repeat("─", 55))
	fmt.Println(red("⚠️  WARNING: This will DELETE your Vercel project!"))
	fmt.Println(red("   Your app will go offline immediately."))
	fmt.Println(yellow("   (Your MongoDB data is safe — it's not managed here)"))
	fmt.Println(strings.Repeat("─", 55))
	fmt.Print("\n   Type 'destroy' to confirm: ")

	var confirm string
	fmt.Scanln(&confirm)
	if confirm != "destroy" {
		fmt.Println(green("\n   Cancelled. Nothing was changed."))
		return
	}

	fmt.Println("\n💥 Running terraform destroy...")
	runTF([]string{"destroy", "-auto-approve"})
	fmt.Println(yellow("\n⚠️  Infrastructure destroyed."))
	fmt.Println(grey("   Run 'go run main.go deploy' to redeploy."))
}

func cmdHelp() {
	fmt.Println(bold("\n🏗️  India Deals Tracker — Infrastructure Manager"))
	fmt.Println(grey("Disaster recovery tool: redeploy your entire app in one command\n"))

	fmt.Println(bold("Commands:"))
	cmds := [][]string{
		{"deploy", "Generate .tf + terraform apply — full deployment"},
		{"plan", "Dry run — show what would change, don't apply"},
		{"generate", "Only write infrastructure.tf, don't run terraform"},
		{"status", "Show what's currently deployed"},
		{"destroy", "Delete everything (use for cloud migration)"},
		{"help", "Show this message"},
	}
	for _, c := range cmds {
		fmt.Printf("  %-12s %s\n", cyan(c[0]), c[1])
	}

	fmt.Println(bold("\nDisaster Recovery Workflow:"))
	fmt.Println(grey("  # If Vercel goes down → switch to another cloud"))
	fmt.Println(grey("  export TARGET_CLOUD=railway"))
	fmt.Println(grey("  go run main.go destroy   # remove from Vercel"))
	fmt.Println(grey("  go run main.go deploy    # redeploy on Railway"))
	fmt.Println(grey("  # App is back online in ~10 minutes"))

	fmt.Println(bold("\nRequired env vars:"))
	vars := [][]string{
		{"VERCEL_API_TOKEN", "vercel.com → Settings → Tokens → Create"},
		{"VERCEL_PROJECT_ID", "vercel.com → your project → Settings → General"},
		{"VERCEL_ORG_ID", "vercel.com → Settings → General → Team ID"},
		{"MONGODB_URI", "your .env.local"},
		{"NEWS_API_KEY", "your .env.local"},
		{"GROQ_API_KEY", "your .env.local"},
		{"CRON_SECRET", "your .env.local"},
		{"GITHUB_REPO", "e.g. vipuljain675-projects/Indian-Deal-Tracker-"},
	}
	for _, v := range vars {
		fmt.Printf("  %-22s %s\n", cyan(v[0]), grey(v[1]))
	}
	fmt.Println()
}

// ── Main ──

func main() {
	// Check terraform installed first
	if !checkTerraform() {
		fmt.Println(red("\n❌ Terraform not installed!"))
		fmt.Println(yellow("   Fix: brew install terraform"))
		fmt.Println(grey("   Then rerun this command."))
		os.Exit(1)
	}

	// Try to auto-load .env.local so user doesn't have to export everything
	// Look in current dir and two levels up (from devops-go/deals-infra/)
	envPaths := []string{
		".env.local",
		"../../.env.local",
		"../../../.env.local",
	}
	for _, path := range envPaths {
		if _, err := os.Stat(path); err == nil {
			readEnvFile(path)
			break
		}
	}

	// Get command
	args := os.Args[1:]
	if len(args) == 0 {
		cmdHelp()
		return
	}
	command := args[0]

	// Help and status don't need full config
	switch command {
	case "help", "--help", "-h":
		cmdHelp()
		return
	case "status":
		cmdStatus()
		return
	case "destroy":
		cmdDestroy()
		return
	}

	// All other commands need full config
	cfg, missing := loadConfig()

	if len(missing) > 0 && command != "generate" {
		fmt.Println(red("\n❌ Missing required environment variables:"))
		for _, m := range missing {
			fmt.Printf("   %s %s\n", red("✗"), m)
		}
		fmt.Println(grey("\n   These are in your .env.local — export them first:"))
		fmt.Println(grey("   export VERCEL_API_TOKEN='your_token'"))
		fmt.Println(grey("   export VERCEL_PROJECT_ID='prj_xxxx'"))
		fmt.Println(grey("   export VERCEL_ORG_ID='team_xxxx'"))
		fmt.Println(grey("   export GITHUB_REPO='owner/repo'"))
		fmt.Println(grey("\n   Run 'go run main.go help' for where to find each value."))
		os.Exit(1)
	}

	switch command {
	case "deploy":
		cmdDeploy(cfg)
	case "plan":
		cmdPlan(cfg)
	case "generate":
		// Use placeholders if IDs not set — useful for previewing the .tf
		if cfg.VercelProjectID == "" {
			cfg.VercelProjectID = "YOUR_PROJECT_ID"
		}
		if cfg.VercelOrgID == "" {
			cfg.VercelOrgID = "YOUR_ORG_ID"
		}
		if cfg.GitRepo == "" {
			cfg.GitRepo = "owner/repo-name"
		}
		cmdGenerate(cfg)
	default:
		fmt.Printf("\n%s '%s'\n", red("❌ Unknown command:"), command)
		cmdHelp()
	}
}